/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.28
 * Generated at: 2025-07-02 05:50:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class companyManagement_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPではGET、POST、またはHEADのみが許可されます。 JasperはOPTIONSも許可しています。");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--*\r\n");
      out.write("：：：色のテーマは緑：：：\r\n");
      out.write("企業管理画面\r\n");
      out.write("\r\n");
      out.write("**********\r\n");
      out.write("\r\n");
      out.write("<!--* 画面：企業管理画面\r\n");
      out.write("        	\r\n");
      out.write("許可されている権限：\r\n");
      out.write("・就職指導部：egd\r\n");
      out.write("・システム管理者：admin\r\n");
      out.write(" \r\n");
      out.write("▼▼▼▼\r\n");
      out.write("*-->\r\n");
      out.write("\r\n");
      out.write("<!--確認まだ-->\r\n");
      out.write("\r\n");
      out.write("<!--KCS_JMS_PROJECT-->\r\n");
      out.write("\r\n");
      out.write("<!-- 企業管理画面用 -->\r\n");
      out.write("\r\n");
      out.write("<!--▼▼▼▼▼スコープから取得する情報　これをもとに判定をしていく -->\r\n");
 
  String username = (String) session.getAttribute("username"); 
  String role     = (String) session.getAttribute("role"); 

      out.write("\r\n");
      out.write("<!--▲▲▲▲▲-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ja\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>企業管理画面</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta name=\"description\" content=\"本アプリは就職対策アプリです。\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- 企業管理画面用CSS -->\r\n");
      out.write("<style>\r\n");
      out.write("/*----------------------------------------------\r\n");
      out.write("  カラー変数\r\n");
      out.write("----------------------------------------------*/\r\n");
      out.write(":root {\r\n");
      out.write("  --primary: #4CAF50;\r\n");
      out.write("  --primary-dark: #388E3C;\r\n");
      out.write("  --bg: #fff;\r\n");
      out.write("  --surface: #f5f7fa;\r\n");
      out.write("  --border: #ddd;\r\n");
      out.write("  --text: #333;\r\n");
      out.write("  --success: #4CAF50;\r\n");
      out.write("  --warning: #FF9800;\r\n");
      out.write("  --danger: #F44336;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*----------------------------------------------\r\n");
      out.write("  ベースリセット\r\n");
      out.write("----------------------------------------------*/\r\n");
      out.write("*,\r\n");
      out.write("*::before,\r\n");
      out.write("*::after {\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  font-family: \"Segoe UI\", \"Hiragino Kaku Gothic ProN\", \"Hiragino Sans\", Meiryo, sans-serif;\r\n");
      out.write("  background: var(--bg);\r\n");
      out.write("  color: var(--text);\r\n");
      out.write("  line-height: 1.6;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("main {\r\n");
      out.write("  max-width: 1200px;\r\n");
      out.write("  padding: 2rem;\r\n");
      out.write("  margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1 {\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  margin-bottom: 2rem;\r\n");
      out.write("  color: var(--primary);\r\n");
      out.write("  font-size: 2rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*----------------------------------------------\r\n");
      out.write("  検索フォーム\r\n");
      out.write("----------------------------------------------*/\r\n");
      out.write(".search-section {\r\n");
      out.write("  background: var(--surface);\r\n");
      out.write("  padding: 1.5rem;\r\n");
      out.write("  border-radius: 8px;\r\n");
      out.write("  margin-bottom: 2rem;\r\n");
      out.write("  box-shadow: 0 2px 4px rgba(0,0,0,0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-section h2 {\r\n");
      out.write("  margin-top: 0;\r\n");
      out.write("  color: var(--primary);\r\n");
      out.write("  font-size: 1.3rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".grid-form .grid-container {\r\n");
      out.write("  display: grid;\r\n");
      out.write("  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));\r\n");
      out.write("  gap: 1rem;\r\n");
      out.write("  margin-bottom: 1rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".field {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  flex-direction: column;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".field label {\r\n");
      out.write("  margin-bottom: 0.5rem;\r\n");
      out.write("  font-weight: bold;\r\n");
      out.write("  color: var(--text);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".field input,\r\n");
      out.write(".field select {\r\n");
      out.write("  padding: 0.75rem;\r\n");
      out.write("  border: 1px solid var(--border);\r\n");
      out.write("  border-radius: 4px;\r\n");
      out.write("  font-size: 1rem;\r\n");
      out.write("  transition: border-color 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".field input:focus,\r\n");
      out.write(".field select:focus {\r\n");
      out.write("  border-color: var(--primary);\r\n");
      out.write("  outline: none;\r\n");
      out.write("  box-shadow: 0 0 0 3px rgba(76, 175, 80, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*----------------------------------------------\r\n");
      out.write("  ボタン\r\n");
      out.write("----------------------------------------------*/\r\n");
      out.write(".btn-wrap {\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  margin-top: 1rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn {\r\n");
      out.write("  padding: 0.75rem 1.5rem;\r\n");
      out.write("  margin: 0 0.5rem;\r\n");
      out.write("  font-size: 1rem;\r\n");
      out.write("  border: none;\r\n");
      out.write("  border-radius: 4px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  transition: all 0.3s ease;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-primary {\r\n");
      out.write("  background: var(--primary);\r\n");
      out.write("  color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-primary:hover {\r\n");
      out.write("  background: var(--primary-dark);\r\n");
      out.write("  transform: translateY(-2px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-secondary {\r\n");
      out.write("  background: var(--surface);\r\n");
      out.write("  color: var(--text);\r\n");
      out.write("  border: 1px solid var(--border);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-secondary:hover {\r\n");
      out.write("  background: #e2e6ea;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-success {\r\n");
      out.write("  background: var(--success);\r\n");
      out.write("  color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-warning {\r\n");
      out.write("  background: var(--warning);\r\n");
      out.write("  color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-danger {\r\n");
      out.write("  background: var(--danger);\r\n");
      out.write("  color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*----------------------------------------------\r\n");
      out.write("  企業一覧テーブル\r\n");
      out.write("----------------------------------------------*/\r\n");
      out.write(".company-table {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  background: white;\r\n");
      out.write("  border-radius: 8px;\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("  box-shadow: 0 2px 8px rgba(0,0,0,0.1);\r\n");
      out.write("  margin-bottom: 2rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".company-table table {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  border-collapse: collapse;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".company-table th,\r\n");
      out.write(".company-table td {\r\n");
      out.write("  padding: 1rem;\r\n");
      out.write("  text-align: left;\r\n");
      out.write("  border-bottom: 1px solid var(--border);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".company-table th {\r\n");
      out.write("  background: var(--primary);\r\n");
      out.write("  color: white;\r\n");
      out.write("  font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".company-table tr:hover {\r\n");
      out.write("  background: var(--surface);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".company-table .actions {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  gap: 0.5rem;\r\n");
      out.write("  flex-wrap: wrap;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*----------------------------------------------\r\n");
      out.write("  モーダル\r\n");
      out.write("----------------------------------------------*/\r\n");
      out.write(".modal {\r\n");
      out.write("  display: none;\r\n");
      out.write("  position: fixed;\r\n");
      out.write("  z-index: 1000;\r\n");
      out.write("  left: 0;\r\n");
      out.write("  top: 0;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  background-color: rgba(0,0,0,0.5);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modal-content {\r\n");
      out.write("  background-color: white;\r\n");
      out.write("  margin: 5% auto;\r\n");
      out.write("  padding: 2rem;\r\n");
      out.write("  border-radius: 8px;\r\n");
      out.write("  width: 90%;\r\n");
      out.write("  max-width: 600px;\r\n");
      out.write("  position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".close {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  right: 1rem;\r\n");
      out.write("  top: 1rem;\r\n");
      out.write("  font-size: 2rem;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  color: #aaa;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".close:hover {\r\n");
      out.write("  color: var(--text);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*----------------------------------------------\r\n");
      out.write("  レスポンシブ\r\n");
      out.write("----------------------------------------------*/\r\n");
      out.write("@media (max-width: 768px) {\r\n");
      out.write("  .grid-form .grid-container {\r\n");
      out.write("    grid-template-columns: 1fr;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  .company-table {\r\n");
      out.write("    font-size: 0.9rem;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  .company-table th,\r\n");
      out.write("  .company-table td {\r\n");
      out.write("    padding: 0.5rem;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  .company-table .actions {\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  .btn {\r\n");
      out.write("    margin: 0.25rem;\r\n");
      out.write("    padding: 0.5rem 1rem;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 権限チェック用スタイル */\r\n");
      out.write(".permission-error {\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  padding: 3rem;\r\n");
      out.write("  color: var(--danger);\r\n");
      out.write("  font-size: 1.2rem;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"container\">\r\n");
      out.write("<!--▼▼▼▼▼ここから「ヘッダー」-->\r\n");
      out.write("<header>\r\n");
      out.write("<!-- ▼▼▼▼ 画面上部アイコン-->\r\n");
      out.write("<h1 id=\"logo\"><a href=\"index.html\"><img src=\"images/logo.png\" alt=\"jms\"></a></h1>\r\n");
      out.write("<!-- ▲▲▲▲ -->\r\n");
      out.write("\r\n");
      out.write("<!--ヘッダー上部分のリスト-->\r\n");
      out.write("<nav>\r\n");
      out.write("<ul>\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("  ");
 if (username != null) { 
      out.write("\r\n");
      out.write("    <li>こんにちは、");
      out.print( username );
      out.write("さん</li>\r\n");
      out.write("    <li>");
      out.print( username );
      out.write("さんの権限は");
      out.print( role );
      out.write("です</li>\r\n");
      out.write("  ");
 } else { 
      out.write("\r\n");
      out.write("    <li><a href=\"login.html\">ログイン</a></li>\r\n");
      out.write("  ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!--* 画面：学生管理画面\r\n");
      out.write("        	\r\n");
      out.write("   許可されている権限：\r\n");
      out.write("        	\r\n");
      out.write("   ・教員：teacher\r\n");
      out.write("   ・校長・教務部長：headmaster\r\n");
      out.write("   ・システム管理者：admin\r\n");
      out.write("        	\r\n");
      out.write("    ▼▼▼▼\r\n");
      out.write("    *-->\r\n");
      out.write("  ");
 if ("teacher".equals(role) 
         || "headmaster".equals(role) 
         || "admin".equals(role)) { 
      out.write("\r\n");
      out.write("    <li>\r\n");
      out.write("      <a href=\"StatusServlet?view=studentManagement\">\r\n");
      out.write("        📚 学生管理画面\r\n");
      out.write("      </a>\r\n");
      out.write("    </li>\r\n");
      out.write("  ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!--* 画面：企業管理画面\r\n");
      out.write("        	\r\n");
      out.write("  許可されている権限：\r\n");
      out.write("        	\r\n");
      out.write("  ・就職指導部：egd\r\n");
      out.write("  ・システム管理者：admin\r\n");
      out.write("        	\r\n");
      out.write("   ▼▼▼▼\r\n");
      out.write("   *-->\r\n");
      out.write("  ");
 if ("egd".equals(role) 
         || "admin".equals(role)) { 
      out.write("\r\n");
      out.write("    <li>\r\n");
      out.write("      <a href=\"StatusServlet?view=CompanyManagement\">\r\n");
      out.write("        🏢 企業管理画面\r\n");
      out.write("      </a>\r\n");
      out.write("    </li>\r\n");
      out.write("  ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <!--* 画面：就職管理画面\r\n");
      out.write("        	\r\n");
      out.write("     許可されている権限：\r\n");
      out.write("        	\r\n");
      out.write("     ・教員：teacher\r\n");
      out.write("     ・校長・教務部長：headmaster\r\n");
      out.write("     ・就職指導部：egd\r\n");
      out.write("     ・システム管理者：admin\r\n");
      out.write("    ・学生： student\r\n");
      out.write("        	\r\n");
      out.write("        	\r\n");
      out.write("   ▼▼▼▼\r\n");
      out.write("   *-->\r\n");
      out.write("  ");
 if ("teacher".equals(role) 
         || "headmaster".equals(role) 
         || "egd".equals(role) 
         || "admin".equals(role) 
         || "student".equals(role)) { 
      out.write("\r\n");
      out.write("    <li>\r\n");
      out.write("      <a href=\"StatusServlet?view=jobHunting\">\r\n");
      out.write("        📄 就職管理画面\r\n");
      out.write("      </a>\r\n");
      out.write("    </li>\r\n");
      out.write("  ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!--* ログアウトボタン\r\n");
      out.write("        	\r\n");
      out.write("   許可されている権限：\r\n");
      out.write("        	\r\n");
      out.write("   ・すべての権限\r\n");
      out.write("        	\r\n");
      out.write("   ▼▼▼▼\r\n");
      out.write("   *-->\r\n");
      out.write("  ");
 if (username != null) { 
      out.write("\r\n");
      out.write("    <li>\r\n");
      out.write("      <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/LogoutServlet\">ログアウト</a>\r\n");
      out.write("    </li>\r\n");
      out.write("  ");
 } 
      out.write("\r\n");
      out.write("</ul>\r\n");
      out.write("</nav>\r\n");
      out.write("</header>\r\n");
      out.write("<!--▲▲▲▲▲ここまで「ヘッダー」-->\r\n");
      out.write("\r\n");
      out.write("<!-- 権限チェック -->\r\n");
 if (!"egd".equals(role) && !"admin".equals(role)) { 
      out.write("\r\n");
      out.write("  <div class=\"permission-error\">\r\n");
      out.write("    <h2>アクセス権限がありません</h2>\r\n");
      out.write("    <p>企業管理画面にアクセスするには、就職指導部またはシステム管理者の権限が必要です。</p>\r\n");
      out.write("    <a href=\"StatusServlet?view=dashboard\" class=\"btn btn-primary\">ダッシュボードに戻る</a>\r\n");
      out.write("  </div>\r\n");
 } else { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<main>\r\n");
      out.write("  <h1>🏢 企業管理画面</h1>\r\n");
      out.write("\r\n");
      out.write("  <!-- 検索セクション -->\r\n");
      out.write("  <section class=\"search-section\">\r\n");
      out.write("    <h2>🔍 企業検索</h2>\r\n");
      out.write("    <form class=\"grid-form\" method=\"GET\" action=\"CompanyServlet\">\r\n");
      out.write("      <input type=\"hidden\" name=\"action\" value=\"search\">\r\n");
      out.write("      <div class=\"grid-container\">\r\n");
      out.write("        <div class=\"field\">\r\n");
      out.write("          <label for=\"companyName\">企業名</label>\r\n");
      out.write("          <input type=\"text\" id=\"companyName\" name=\"companyName\" placeholder=\"企業名を入力\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"field\">\r\n");
      out.write("          <label for=\"industry\">業界</label>\r\n");
      out.write("          <select id=\"industry\" name=\"industry\">\r\n");
      out.write("            <option value=\"\">すべての業界</option>\r\n");
      out.write("            <option value=\"IT\">IT・ソフトウェア</option>\r\n");
      out.write("            <option value=\"manufacturing\">製造業</option>\r\n");
      out.write("            <option value=\"finance\">金融・保険</option>\r\n");
      out.write("            <option value=\"retail\">小売・流通</option>\r\n");
      out.write("            <option value=\"service\">サービス業</option>\r\n");
      out.write("            <option value=\"construction\">建設業</option>\r\n");
      out.write("            <option value=\"medical\">医療・福祉</option>\r\n");
      out.write("            <option value=\"education\">教育</option>\r\n");
      out.write("            <option value=\"other\">その他</option>\r\n");
      out.write("          </select>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"field\">\r\n");
      out.write("          <label for=\"location\">所在地</label>\r\n");
      out.write("          <input type=\"text\" id=\"location\" name=\"location\" placeholder=\"都道府県を入力\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"field\">\r\n");
      out.write("          <label for=\"status\">採用状況</label>\r\n");
      out.write("          <select id=\"status\" name=\"status\">\r\n");
      out.write("            <option value=\"\">すべて</option>\r\n");
      out.write("            <option value=\"active\">採用中</option>\r\n");
      out.write("            <option value=\"inactive\">採用終了</option>\r\n");
      out.write("            <option value=\"planning\">採用予定</option>\r\n");
      out.write("          </select>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"btn-wrap\">\r\n");
      out.write("        <button type=\"submit\" class=\"btn btn-primary\">検索</button>\r\n");
      out.write("        <button type=\"reset\" class=\"btn btn-secondary\">リセット</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </form>\r\n");
      out.write("  </section>\r\n");
      out.write("\r\n");
      out.write("  <!-- 企業登録ボタン -->\r\n");
      out.write("  <div class=\"btn-wrap\" style=\"margin-bottom: 2rem;\">\r\n");
      out.write("    <button onclick=\"openAddModal()\" class=\"btn btn-success\">➕ 新規企業登録</button>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- 企業一覧テーブル -->\r\n");
      out.write("  <section class=\"company-table\">\r\n");
      out.write("    <table>\r\n");
      out.write("      <thead>\r\n");
      out.write("        <tr>\r\n");
      out.write("          <th>企業名</th>\r\n");
      out.write("          <th>業界</th>\r\n");
      out.write("          <th>所在地</th>\r\n");
      out.write("          <th>連絡先</th>\r\n");
      out.write("          <th>採用状況</th>\r\n");
      out.write("          <th>登録日</th>\r\n");
      out.write("          <th>操作</th>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </thead>\r\n");
      out.write("      <tbody>\r\n");
      out.write("        <!-- サンプルデータ（実際の実装ではデータベースから取得） -->\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td>株式会社サンプルIT</td>\r\n");
      out.write("          <td>IT・ソフトウェア</td>\r\n");
      out.write("          <td>東京都</td>\r\n");
      out.write("          <td>03-1234-5678</td>\r\n");
      out.write("          <td><span style=\"color: var(--success);\">採用中</span></td>\r\n");
      out.write("          <td>2024-01-15</td>\r\n");
      out.write("          <td class=\"actions\">\r\n");
      out.write("            <button onclick=\"openEditModal(1)\" class=\"btn btn-warning\">編集</button>\r\n");
      out.write("            <button onclick=\"deleteCompany(1)\" class=\"btn btn-danger\">削除</button>\r\n");
      out.write("          </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td>サンプル製造株式会社</td>\r\n");
      out.write("          <td>製造業</td>\r\n");
      out.write("          <td>大阪府</td>\r\n");
      out.write("          <td>06-9876-5432</td>\r\n");
      out.write("          <td><span style=\"color: var(--warning);\">採用予定</span></td>\r\n");
      out.write("          <td>2024-01-10</td>\r\n");
      out.write("          <td class=\"actions\">\r\n");
      out.write("            <button onclick=\"openEditModal(2)\" class=\"btn btn-warning\">編集</button>\r\n");
      out.write("            <button onclick=\"deleteCompany(2)\" class=\"btn btn-danger\">削除</button>\r\n");
      out.write("          </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td>サンプル金融銀行</td>\r\n");
      out.write("          <td>金融・保険</td>\r\n");
      out.write("          <td>愛知県</td>\r\n");
      out.write("          <td>052-5555-1234</td>\r\n");
      out.write("          <td><span style=\"color: var(--danger);\">採用終了</span></td>\r\n");
      out.write("          <td>2024-01-05</td>\r\n");
      out.write("          <td class=\"actions\">\r\n");
      out.write("            <button onclick=\"openEditModal(3)\" class=\"btn btn-warning\">編集</button>\r\n");
      out.write("            <button onclick=\"deleteCompany(3)\" class=\"btn btn-danger\">削除</button>\r\n");
      out.write("          </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </tbody>\r\n");
      out.write("    </table>\r\n");
      out.write("  </section>\r\n");
      out.write("</main>\r\n");
      out.write("\r\n");
      out.write("<!-- 企業登録・編集モーダル -->\r\n");
      out.write("<div id=\"companyModal\" class=\"modal\">\r\n");
      out.write("  <div class=\"modal-content\">\r\n");
      out.write("    <span class=\"close\" onclick=\"closeModal()\">&times;</span>\r\n");
      out.write("    <h2 id=\"modalTitle\">企業登録</h2>\r\n");
      out.write("    <form id=\"companyForm\" method=\"POST\" action=\"CompanyServlet\">\r\n");
      out.write("      <input type=\"hidden\" id=\"companyId\" name=\"companyId\">\r\n");
      out.write("      <input type=\"hidden\" id=\"formAction\" name=\"action\" value=\"add\">\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"grid-container\">\r\n");
      out.write("        <div class=\"field\">\r\n");
      out.write("          <label for=\"modalCompanyName\">企業名 *</label>\r\n");
      out.write("          <input type=\"text\" id=\"modalCompanyName\" name=\"companyName\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"field\">\r\n");
      out.write("          <label for=\"modalIndustry\">業界 *</label>\r\n");
      out.write("          <select id=\"modalIndustry\" name=\"industry\" required>\r\n");
      out.write("            <option value=\"\">業界を選択</option>\r\n");
      out.write("            <option value=\"IT\">IT・ソフトウェア</option>\r\n");
      out.write("            <option value=\"manufacturing\">製造業</option>\r\n");
      out.write("            <option value=\"finance\">金融・保険</option>\r\n");
      out.write("            <option value=\"retail\">小売・流通</option>\r\n");
      out.write("            <option value=\"service\">サービス業</option>\r\n");
      out.write("            <option value=\"construction\">建設業</option>\r\n");
      out.write("            <option value=\"medical\">医療・福祉</option>\r\n");
      out.write("            <option value=\"education\">教育</option>\r\n");
      out.write("            <option value=\"other\">その他</option>\r\n");
      out.write("          </select>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"field\">\r\n");
      out.write("          <label for=\"modalLocation\">所在地 *</label>\r\n");
      out.write("          <input type=\"text\" id=\"modalLocation\" name=\"location\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"field\">\r\n");
      out.write("          <label for=\"modalPhone\">電話番号</label>\r\n");
      out.write("          <input type=\"tel\" id=\"modalPhone\" name=\"phone\" placeholder=\"03-1234-5678\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"field\">\r\n");
      out.write("          <label for=\"modalEmail\">メールアドレス</label>\r\n");
      out.write("          <input type=\"email\" id=\"modalEmail\" name=\"email\" placeholder=\"example@company.com\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"field\">\r\n");
      out.write("          <label for=\"modalStatus\">採用状況 *</label>\r\n");
      out.write("          <select id=\"modalStatus\" name=\"status\" required>\r\n");
      out.write("            <option value=\"active\">採用中</option>\r\n");
      out.write("            <option value=\"inactive\">採用終了</option>\r\n");
      out.write("            <option value=\"planning\">採用予定</option>\r\n");
      out.write("          </select>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"field\">\r\n");
      out.write("          <label for=\"modalWebsite\">Webサイト</label>\r\n");
      out.write("          <input type=\"url\" id=\"modalWebsite\" name=\"website\" placeholder=\"https://example.com\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"field\">\r\n");
      out.write("          <label for=\"modalDescription\">企業説明</label>\r\n");
      out.write("          <textarea id=\"modalDescription\" name=\"description\" rows=\"4\" placeholder=\"企業の特徴や事業内容を入力してください\"></textarea>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"btn-wrap\">\r\n");
      out.write("        <button type=\"submit\" class=\"btn btn-primary\">保存</button>\r\n");
      out.write("        <button type=\"button\" onclick=\"closeModal()\" class=\"btn btn-secondary\">キャンセル</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </form>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- JavaScript -->\r\n");
      out.write("<script>\r\n");
      out.write("// モーダル制御\r\n");
      out.write("function openAddModal() {\r\n");
      out.write("  document.getElementById('modalTitle').textContent = '企業登録';\r\n");
      out.write("  document.getElementById('formAction').value = 'add';\r\n");
      out.write("  document.getElementById('companyForm').reset();\r\n");
      out.write("  document.getElementById('companyModal').style.display = 'block';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function openEditModal(companyId) {\r\n");
      out.write("  document.getElementById('modalTitle').textContent = '企業編集';\r\n");
      out.write("  document.getElementById('formAction').value = 'edit';\r\n");
      out.write("  document.getElementById('companyId').value = companyId;\r\n");
      out.write("  \r\n");
      out.write("  // サンプルデータ（実際の実装ではAjaxでデータを取得）\r\n");
      out.write("  const sampleData = {\r\n");
      out.write("    1: {\r\n");
      out.write("      companyName: '株式会社サンプルIT',\r\n");
      out.write("      industry: 'IT',\r\n");
      out.write("      location: '東京都',\r\n");
      out.write("      phone: '03-1234-5678',\r\n");
      out.write("      email: 'info@sampleit.co.jp',\r\n");
      out.write("      status: 'active',\r\n");
      out.write("      website: 'https://sampleit.co.jp',\r\n");
      out.write("      description: 'ITソリューションを提供する企業です。'\r\n");
      out.write("    },\r\n");
      out.write("    2: {\r\n");
      out.write("      companyName: 'サンプル製造株式会社',\r\n");
      out.write("      industry: 'manufacturing',\r\n");
      out.write("      location: '大阪府',\r\n");
      out.write("      phone: '06-9876-5432',\r\n");
      out.write("      email: 'contact@sample-manufacturing.co.jp',\r\n");
      out.write("      status: 'planning',\r\n");
      out.write("      website: 'https://sample-manufacturing.co.jp',\r\n");
      out.write("      description: '製造業を営む企業です。'\r\n");
      out.write("    },\r\n");
      out.write("    3: {\r\n");
      out.write("      companyName: 'サンプル金融銀行',\r\n");
      out.write("      industry: 'finance',\r\n");
      out.write("      location: '愛知県',\r\n");
      out.write("      phone: '052-5555-1234',\r\n");
      out.write("      email: 'hr@sample-bank.co.jp',\r\n");
      out.write("      status: 'inactive',\r\n");
      out.write("      website: 'https://sample-bank.co.jp',\r\n");
      out.write("      description: '金融サービスを提供する銀行です。'\r\n");
      out.write("    }\r\n");
      out.write("  };\r\n");
      out.write("  \r\n");
      out.write("  const data = sampleData[companyId];\r\n");
      out.write("  if (data) {\r\n");
      out.write("    document.getElementById('modalCompanyName').value = data.companyName;\r\n");
      out.write("    document.getElementById('modalIndustry').value = data.industry;\r\n");
      out.write("    document.getElementById('modalLocation').value = data.location;\r\n");
      out.write("    document.getElementById('modalPhone').value = data.phone;\r\n");
      out.write("    document.getElementById('modalEmail').value = data.email;\r\n");
      out.write("    document.getElementById('modalStatus').value = data.status;\r\n");
      out.write("    document.getElementById('modalWebsite').value = data.website;\r\n");
      out.write("    document.getElementById('modalDescription').value = data.description;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  document.getElementById('companyModal').style.display = 'block';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function closeModal() {\r\n");
      out.write("  document.getElementById('companyModal').style.display = 'none';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function deleteCompany(companyId) {\r\n");
      out.write("  if (confirm('この企業を削除してもよろしいですか？')) {\r\n");
      out.write("    // 実際の実装ではAjaxで削除処理を実行\r\n");
      out.write("    alert('企業ID: ' + companyId + ' を削除しました。');\r\n");
      out.write("    location.reload();\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// モーダル外クリックで閉じる\r\n");
      out.write("window.onclick = function(event) {\r\n");
      out.write("  const modal = document.getElementById('companyModal');\r\n");
      out.write("  if (event.target == modal) {\r\n");
      out.write("    closeModal();\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// フォーム送信時の処理\r\n");
      out.write("document.getElementById('companyForm').addEventListener('submit', function(e) {\r\n");
      out.write("  e.preventDefault();\r\n");
      out.write("  \r\n");
      out.write("  // 実際の実装ではAjaxでフォームデータを送信\r\n");
      out.write("  const formData = new FormData(this);\r\n");
      out.write("  const action = formData.get('action');\r\n");
      out.write("  \r\n");
      out.write("  if (action === 'add') {\r\n");
      out.write("    alert('企業を登録しました。');\r\n");
      out.write("  } else if (action === 'edit') {\r\n");
      out.write("    alert('企業情報を更新しました。');\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  closeModal();\r\n");
      out.write("  location.reload();\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
