/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.28
 * Generated at: 2025-07-02 05:50:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class CreateStudent_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPではGET、POST、またはHEADのみが許可されます。 JasperはOPTIONSも許可しています。");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ja\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>JMSアプリ - 新規学生登録</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta name=\"description\" content=\"本アプリは就職対策アプリです。\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("<style>\r\n");
      out.write("    /* システム上見やすさを追求した新規学生登録画面デザイン */\r\n");
      out.write("    \r\n");
      out.write("    /* 全体の設定 */\r\n");
      out.write("    .create-student-page {\r\n");
      out.write("        background: #f8f9fa;\r\n");
      out.write("        color: #2c3e50;\r\n");
      out.write("        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("        line-height: 1.6;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .create-student-container {\r\n");
      out.write("        max-width: 800px;\r\n");
      out.write("        margin: 0 auto;\r\n");
      out.write("        padding: 24px;\r\n");
      out.write("        min-height: 100vh;\r\n");
      out.write("        background: #ffffff;\r\n");
      out.write("        box-shadow: 0 0 20px rgba(0, 0, 0, 0.05);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ページヘッダー - 視認性向上 */\r\n");
      out.write("    .page-header {\r\n");
      out.write("        background: linear-gradient(135deg, #2C7744 0%, #5CA564 100%);\r\n");
      out.write("        border-radius: 12px;\r\n");
      out.write("        padding: 32px;\r\n");
      out.write("        margin-bottom: 32px;\r\n");
      out.write("        box-shadow: 0 4px 20px rgba(44, 119, 68, 0.15);\r\n");
      out.write("        color: #000000;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        position: relative;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .page-title {\r\n");
      out.write("        font-size: 32px;\r\n");
      out.write("        color: #000000;\r\n");
      out.write("        margin-bottom: 12px;\r\n");
      out.write("        font-weight: 700;\r\n");
      out.write("        text-shadow: 0 1px 2px rgba(255, 255, 255, 0.3);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .breadcrumb {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        gap: 12px;\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        color: #000000;\r\n");
      out.write("        margin-top: 16px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .breadcrumb a {\r\n");
      out.write("        color: #000000;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        transition: all 0.2s ease;\r\n");
      out.write("        padding: 6px 12px;\r\n");
      out.write("        border-radius: 6px;\r\n");
      out.write("        background: rgba(255, 255, 255, 0.3);\r\n");
      out.write("        border: 1px solid rgba(255, 255, 255, 0.4);\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .breadcrumb a:hover {\r\n");
      out.write("        background: rgba(255, 255, 255, 0.5);\r\n");
      out.write("        transform: translateY(-1px);\r\n");
      out.write("        color: #000000;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .breadcrumb .separator {\r\n");
      out.write("        color: #000000;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* 登録フォーム - 視認性と操作性の向上 */\r\n");
      out.write("    .registration-form {\r\n");
      out.write("        background: white;\r\n");
      out.write("        border-radius: 12px;\r\n");
      out.write("        padding: 32px;\r\n");
      out.write("        box-shadow: 0 2px 12px rgba(0, 0, 0, 0.08);\r\n");
      out.write("        border: 1px solid #e9ecef;\r\n");
      out.write("        margin-bottom: 24px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-group {\r\n");
      out.write("        margin-bottom: 24px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-group label {\r\n");
      out.write("        display: block;\r\n");
      out.write("        margin-bottom: 8px;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        color: #2c3e50;\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-group input,\r\n");
      out.write("    .form-group select {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        padding: 12px 16px;\r\n");
      out.write("        border: 1px solid #e9ecef;\r\n");
      out.write("        border-radius: 8px;\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("        transition: all 0.2s ease;\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-group input:focus,\r\n");
      out.write("    .form-group select:focus {\r\n");
      out.write("        outline: none;\r\n");
      out.write("        border-color: #2C7744;\r\n");
      out.write("        box-shadow: 0 0 0 3px rgba(44, 119, 68, 0.1);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-row {\r\n");
      out.write("        display: grid;\r\n");
      out.write("        grid-template-columns: 1fr 1fr;\r\n");
      out.write("        gap: 16px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .required {\r\n");
      out.write("        color: #e74c3c;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ボタン */\r\n");
      out.write("    .form-buttons {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        gap: 16px;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        margin-top: 32px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn {\r\n");
      out.write("        padding: 14px 28px;\r\n");
      out.write("        border-radius: 8px;\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        transition: all 0.2s ease;\r\n");
      out.write("        border: none;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        min-width: 120px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-primary {\r\n");
      out.write("        background: linear-gradient(135deg, #2C7744 0%, #5CA564 100%);\r\n");
      out.write("        color: white;\r\n");
      out.write("        box-shadow: 0 2px 8px rgba(44, 119, 68, 0.2);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-primary:hover {\r\n");
      out.write("        transform: translateY(-1px);\r\n");
      out.write("        box-shadow: 0 4px 15px rgba(44, 119, 68, 0.3);\r\n");
      out.write("        color: white;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-secondary {\r\n");
      out.write("        background: linear-gradient(135deg, #6c757d 0%, #495057 100%);\r\n");
      out.write("        color: white;\r\n");
      out.write("        box-shadow: 0 2px 8px rgba(108, 117, 125, 0.2);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-secondary:hover {\r\n");
      out.write("        transform: translateY(-1px);\r\n");
      out.write("        box-shadow: 0 4px 15px rgba(108, 117, 125, 0.3);\r\n");
      out.write("        color: white;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"create-student-page\">\r\n");
      out.write("    <div class=\"create-student-container\">\r\n");
      out.write("        <!-- ページヘッダー -->\r\n");
      out.write("        <div class=\"page-header\">\r\n");
      out.write("            <h1 class=\"page-title\">新規学生登録</h1>\r\n");
      out.write("            <div class=\"breadcrumb\">\r\n");
      out.write("                <a href=\"StatusServlet?status=DashBoard\">ダッシュボード</a>\r\n");
      out.write("                <span class=\"separator\">></span>\r\n");
      out.write("                <a href=\"StatusServlet?status=studentManagement\">学生管理</a>\r\n");
      out.write("                <span class=\"separator\">></span>\r\n");
      out.write("                <span>新規学生登録</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- エラーメッセージ表示 -->\r\n");
      out.write("        ");
 if (request.getAttribute("errorMessage") != null) { 
      out.write("\r\n");
      out.write("            <div class=\"message error-message\" style=\"background: #f8d7da; color: #721c24; border: 1px solid #f5c6cb; border-radius: 8px; padding: 16px; margin-bottom: 24px; text-align: center; font-weight: 600;\">\r\n");
      out.write("                ❌ ");
      out.print( request.getAttribute("errorMessage") );
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- 登録フォーム -->\r\n");
      out.write("        <div class=\"registration-form\">\r\n");
      out.write("            <form action=\"StudentServlet\" method=\"post\">\r\n");
      out.write("                <input type=\"hidden\" name=\"action\" value=\"create\">\r\n");
      out.write("                \r\n");
      out.write("                <!-- 基本情報 -->\r\n");
      out.write("                <h3 style=\"margin-bottom: 20px; color: #2c3e50; border-bottom: 2px solid #2C7744; padding-bottom: 8px;\">基本情報</h3>\r\n");
      out.write("                <div class=\"form-row\">\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"admissionYear\">入学年（西暦）<span class=\"required\">*</span></label>\r\n");
      out.write("                        <input type=\"number\" id=\"admissionYear\" name=\"admissionYear\" min=\"2000\" max=\"2099\" required placeholder=\"例: 2022\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-row\">\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"classType\">クラス種別 <span class=\"required\">*</span></label>\r\n");
      out.write("                        <select id=\"classType\" name=\"classType\" required>\r\n");
      out.write("                            <option value=\"\">選択してください</option>\r\n");
      out.write("                            <option value=\"R\">R（大学併修）</option>\r\n");
      out.write("                            <option value=\"S\">S（エンジニア・クリエータ科システム分野）</option>\r\n");
      out.write("                            <option value=\"M\">M（エンジニア・クリエータ科ゲーム分野）</option>\r\n");
      out.write("                            <option value=\"J\">J（プログラム・デザイン科システム分野）</option>\r\n");
      out.write("                            <option value=\"G\">G（プログラム・デザイン科ゲーム分野）</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"classGrade\">学年 <span class=\"required\">*</span></label>\r\n");
      out.write("                        <select id=\"classGrade\" name=\"classGrade\" required>\r\n");
      out.write("                            <option value=\"\">選択してください</option>\r\n");
      out.write("                            <option value=\"1\">1年</option>\r\n");
      out.write("                            <option value=\"2\">2年</option>\r\n");
      out.write("                            <option value=\"3\">3年</option>\r\n");
      out.write("                            <option value=\"4\">4年</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"classGroup\">組 <span class=\"required\">*</span></label>\r\n");
      out.write("                        <select id=\"classGroup\" name=\"classGroup\" required>\r\n");
      out.write("                            <option value=\"\">選択してください</option>\r\n");
      out.write("                            <option value=\"1\">1組</option>\r\n");
      out.write("                            <option value=\"2\">2組</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"className\">クラス名（自動生成）</label>\r\n");
      out.write("                    <input type=\"text\" id=\"className\" name=\"className\" readonly placeholder=\"自動生成\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-row\">\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"attendanceNo\">出席番号 <span class=\"required\">*</span></label>\r\n");
      out.write("                        <input type=\"number\" id=\"attendanceNo\" name=\"attendanceNo\" min=\"1\" max=\"999\" required placeholder=\"例: 1\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"studentId\">学籍番号 </label>\r\n");
      out.write("                    <input type=\"text\" id=\"studentId\" name=\"studentId\" required maxlength=\"8\" readonly placeholder=\"自動生成\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-row\">\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"name\">氏名 <span class=\"required\">*</span></label>\r\n");
      out.write("                        <input type=\"text\" id=\"name\" name=\"name\" required placeholder=\"例: 山田太郎\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"kana\">フリガナ <span class=\"required\">*</span></label>\r\n");
      out.write("                        <input type=\"text\" id=\"kana\" name=\"kana\" required placeholder=\"例: ヤマダタロウ\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-row\">\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"gender\">性別 <span class=\"required\">*</span></label>\r\n");
      out.write("                        <select id=\"gender\" name=\"gender\" required>\r\n");
      out.write("                            <option value=\"\">選択してください</option>\r\n");
      out.write("                            <option value=\"男\">男</option>\r\n");
      out.write("                            <option value=\"女\">女</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- 学籍情報 -->\r\n");
      out.write("                <h3 style=\"margin: 32px 0 20px 0; color: #2c3e50; border-bottom: 2px solid #2C7744; padding-bottom: 8px;\">学籍情報</h3>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"form-row\">\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"department\">学部 <span class=\"required\">*</span></label>\r\n");
      out.write("                        <select id=\"department\" name=\"department\" required>\r\n");
      out.write("                            <option value=\"情報工学\">情報工学</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"major\">専攻・学科</label>\r\n");
      out.write("                    <select id=\"major\" name=\"major\" required>\r\n");
      out.write("                        <option value=\"大学併修\">大学併修</option>\r\n");
      out.write("                        <option value=\"エンジニア・クリエータ科システム分野\">エンジニア・クリエータ科システム分野</option>\r\n");
      out.write("                        <option value=\"エンジニア・クリエータ科ゲーム分野\">エンジニア・クリエータ科ゲーム分野</option>\r\n");
      out.write("                        <option value=\"プログラム・デザイン科システム分野\">プログラム・デザイン科システム分野</option>\r\n");
      out.write("                        <option value=\"プログラム・デザイン科ゲーム分野\">プログラム・デザイン科ゲーム分野</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- 就活情報 -->\r\n");
      out.write("                <h3 style=\"margin: 32px 0 20px 0; color: #2c3e50; border-bottom: 2px solid #2C7744; padding-bottom: 8px;\">就活情報</h3>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"form-row\">\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"jobHuntingStatus\">就活状況</label>\r\n");
      out.write("                        <select id=\"jobHuntingStatus\" name=\"jobHuntingStatus\">\r\n");
      out.write("                            <option value=\"\">選択してください</option>\r\n");
      out.write("                            <option value=\"未開始\">未開始</option>\r\n");
      out.write("                            <option value=\"準備中\">準備中</option>\r\n");
      out.write("                            <option value=\"活動中\">活動中</option>\r\n");
      out.write("                            <option value=\"内定済み\">内定済み</option>\r\n");
      out.write("                            <option value=\"就職決定\">就職決定</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"targetIndustry\">希望業種</label>\r\n");
      out.write("                        <select id=\"targetIndustry\" name=\"targetIndustry\">\r\n");
      out.write("                            <option value=\"\">選択してください</option>\r\n");
      out.write("                            <option value=\"IT・通信\">IT・通信</option>\r\n");
      out.write("                            <option value=\"製造業\">製造業</option>\r\n");
      out.write("                            <option value=\"金融・保険\">金融・保険</option>\r\n");
      out.write("                            <option value=\"商社・流通\">商社・流通</option>\r\n");
      out.write("                            <option value=\"建設・不動産\">建設・不動産</option>\r\n");
      out.write("                            <option value=\"メディア・広告\">メディア・広告</option>\r\n");
      out.write("                            <option value=\"サービス業\">サービス業</option>\r\n");
      out.write("                            <option value=\"公務員\">公務員</option>\r\n");
      out.write("                            <option value=\"その他\">その他</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"notes\">備考</label>\r\n");
      out.write("                    <textarea id=\"notes\" name=\"notes\" rows=\"4\" style=\"width: 100%; padding: 12px 16px; border: 1px solid #e9ecef; border-radius: 8px; font-size: 16px; resize: vertical;\" placeholder=\"特記事項があれば記入してください\"></textarea>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- ボタン -->\r\n");
      out.write("                <div class=\"form-buttons\">\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary\">登録する</button>\r\n");
      out.write("                    <a href=\"StatusServlet?status=studentManagement\" class=\"btn btn-secondary\">キャンセル</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        // フォームバリデーション\r\n");
      out.write("        document.querySelector('form').addEventListener('submit', function(e) {\r\n");
      out.write("            const studentId = document.getElementById('studentId').value;\r\n");
      out.write("            const name = document.getElementById('name').value;\r\n");
      out.write("            const kana = document.getElementById('kana').value;\r\n");
      out.write("            const department = document.getElementById('department').value;\r\n");
      out.write("\r\n");
      out.write("            // 必須項目チェック\r\n");
      out.write("            if (!studentId || !name || !kana || !department) {\r\n");
      out.write("                e.preventDefault();\r\n");
      out.write("                alert('必須項目を入力してください。');\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            // 学籍番号の形式チェック（8桁）\r\n");
      out.write("            if (!/^[0-9]{8}$/.test(studentId)) {\r\n");
      out.write("                e.preventDefault();\r\n");
      out.write("                alert('学籍番号は8桁の数字で自動生成されます。');\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("        document.getElementById('kana').addEventListener('input', function() {\r\n");
      out.write("            this.value = this.value.toUpperCase();\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // --- 学籍番号自動生成（表ルール対応） ---\r\n");
      out.write("        function generateStudentId() {\r\n");
      out.write("            const year = document.getElementById('admissionYear').value;\r\n");
      out.write("            const type = document.getElementById('classType').value;\r\n");
      out.write("            const grade = document.getElementById('classGrade').value;\r\n");
      out.write("            const group = document.getElementById('classGroup').value;\r\n");
      out.write("            const classCodeMap = {\r\n");
      out.write("                'R': '11',\r\n");
      out.write("                'S': '21',\r\n");
      out.write("                'M': '22',\r\n");
      out.write("                'J': '31',\r\n");
      out.write("                'G': '32',\r\n");
      out.write("            };\r\n");
      out.write("            let studentId = '';\r\n");
      out.write("            if (year && type && grade && group) {\r\n");
      out.write("                const yy = year.slice(-2);\r\n");
      out.write("                const mid = classCodeMap[type] || '';\r\n");
      out.write("                const rand = Math.floor(Math.random() * 1000).toString().padStart(3, '0');\r\n");
      out.write("                studentId = '2' + yy + mid + rand; // 8桁\r\n");
      out.write("            }\r\n");
      out.write("            document.getElementById('studentId').value = studentId;\r\n");
      out.write("        }\r\n");
      out.write("        document.getElementById('admissionYear').addEventListener('change', generateStudentId);\r\n");
      out.write("        document.getElementById('classType').addEventListener('change', generateStudentId);\r\n");
      out.write("        document.getElementById('classGrade').addEventListener('change', generateStudentId);\r\n");
      out.write("        document.getElementById('classGroup').addEventListener('change', generateStudentId);\r\n");
      out.write("\r\n");
      out.write("        function updateClassNameRxAx() {\r\n");
      out.write("            const type = document.getElementById('classType').value;\r\n");
      out.write("            const grade = document.getElementById('classGrade').value;\r\n");
      out.write("            const group = document.getElementById('classGroup').value;\r\n");
      out.write("            let className = '';\r\n");
      out.write("            if (type && grade && group) {\r\n");
      out.write("                // 固定文字を決定\r\n");
      out.write("                let fixedChar = '666666';\r\n");
      out.write("                if (type === 'R' || type === 'S') fixedChar = 'A';\r\n");
      out.write("                else if (type === 'M' || type === 'G') fixedChar = 'G';\r\n");
      out.write("                else if (type === 'J') fixedChar = 'S';\r\n");
      out.write("                className = `");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${type}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${grade}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fixedChar}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${group}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`;\r\n");
      out.write("            }\r\n");
      out.write("            document.getElementById('className').value = className;\r\n");
      out.write("        }\r\n");
      out.write("        document.getElementById('className').addEventListener('change', updateClassNameRxAx);\r\n");
      out.write("        document.getElementById('classType').addEventListener('change', updateClassNameRxAx);\r\n");
      out.write("        document.getElementById('classGrade').addEventListener('change', updateClassNameRxAx);\r\n");
      out.write("        document.getElementById('classGroup').addEventListener('change', updateClassNameRxAx);\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html> ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
