/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.28
 * Generated at: 2025-07-02 05:49:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class DashBoard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPではGET、POST、またはHEADのみが許可されます。 JasperはOPTIONSも許可しています。");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--*\r\n");
      out.write("：：：色のテーマは緑：：：\r\n");
      out.write("ダッシュボード用画面\r\n");
      out.write("\r\n");
      out.write("******教員-生徒-どちらにも表示されるページ****\r\n");
      out.write("******権限によって表示されるボタンが変わる****\r\n");
      out.write("\r\n");
      out.write(":::権限一覧:::\r\n");
      out.write("\r\n");
      out.write("{\r\n");
      out.write("  \"teacher\":           \"教員\",\r\n");
      out.write("  \"headmaster\": \"教務部長_校長\",\r\n");
      out.write("  \"egd\":      \"就職指導部\",\r\n");
      out.write("  \"admin\":             \"管理者\",\r\n");
      out.write("  \"student\":           \"学生\"\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("||**すべての中心**||\r\n");
      out.write("\r\n");
      out.write("**\r\n");
      out.write("\r\n");
      out.write("*-->\r\n");
      out.write("\r\n");
      out.write("<!--KCS_JMS_PROJECT-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ja\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>JMSアプリ - ダッシュボード</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta name=\"description\" content=\"本アプリは就職対策アプリです。\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    /* システム上見やすさを追求したダッシュボードデザイン */\r\n");
      out.write("    \r\n");
      out.write("    /* 全体の設定 */\r\n");
      out.write("    .dashboard-page {\r\n");
      out.write("        background: #f8f9fa;\r\n");
      out.write("        color: #2c3e50;\r\n");
      out.write("        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("        line-height: 1.6;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ダッシュボード全体 */\r\n");
      out.write("    .dashboard-container {\r\n");
      out.write("        max-width: 1400px;\r\n");
      out.write("        margin: 0 auto;\r\n");
      out.write("        padding: 24px;\r\n");
      out.write("        min-height: 100vh;\r\n");
      out.write("        background: #ffffff;\r\n");
      out.write("        box-shadow: 0 0 20px rgba(0, 0, 0, 0.05);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ヘッダー - 視認性向上 */\r\n");
      out.write("    .dashboard-header {\r\n");
      out.write("        background: linear-gradient(135deg, #2C7744 0%, #5CA564 100%);\r\n");
      out.write("        border-radius: 12px;\r\n");
      out.write("        padding: 32px;\r\n");
      out.write("        margin-bottom: 32px;\r\n");
      out.write("        box-shadow: 0 4px 20px rgba(44, 119, 68, 0.15);\r\n");
      out.write("        color: white;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .user-info {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: space-between;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        flex-wrap: wrap;\r\n");
      out.write("        gap: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .user-welcome {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        gap: 16px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .user-avatar {\r\n");
      out.write("        width: 64px;\r\n");
      out.write("        height: 64px;\r\n");
      out.write("        border-radius: 50%;\r\n");
      out.write("        background: rgba(255, 255, 255, 0.2);\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        color: white;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        font-size: 24px;\r\n");
      out.write("        border: 3px solid rgba(255, 255, 255, 0.3);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .user-details h2 {\r\n");
      out.write("        margin: 0 0 8px 0;\r\n");
      out.write("        color: white;\r\n");
      out.write("        font-size: 28px;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        text-shadow: 0 1px 2px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .role-badge {\r\n");
      out.write("        background: rgba(255, 255, 255, 0.2);\r\n");
      out.write("        color: white;\r\n");
      out.write("        padding: 8px 16px;\r\n");
      out.write("        border-radius: 20px;\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        border: 1px solid rgba(255, 255, 255, 0.3);\r\n");
      out.write("        backdrop-filter: blur(10px);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .logout-btn {\r\n");
      out.write("        background: rgba(255, 255, 255, 0.15);\r\n");
      out.write("        color: white;\r\n");
      out.write("        padding: 12px 24px;\r\n");
      out.write("        border: 2px solid rgba(255, 255, 255, 0.3);\r\n");
      out.write("        border-radius: 8px;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("        transition: all 0.2s ease;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("        backdrop-filter: blur(10px);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .logout-btn:hover {\r\n");
      out.write("        background: rgba(255, 255, 255, 0.25);\r\n");
      out.write("        border-color: rgba(255, 255, 255, 0.5);\r\n");
      out.write("        transform: translateY(-1px);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* メインコンテンツ - 情報階層の改善 */\r\n");
      out.write("    .dashboard-main {\r\n");
      out.write("        display: grid;\r\n");
      out.write("        grid-template-columns: repeat(auto-fit, minmax(350px, 1fr));\r\n");
      out.write("        gap: 24px;\r\n");
      out.write("        margin-bottom: 32px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* 機能カード - 視認性と操作性の向上 */\r\n");
      out.write("    .feature-card {\r\n");
      out.write("        background: white;\r\n");
      out.write("        border-radius: 12px;\r\n");
      out.write("        padding: 32px;\r\n");
      out.write("        box-shadow: 0 2px 12px rgba(0, 0, 0, 0.08);\r\n");
      out.write("        border: 1px solid #e9ecef;\r\n");
      out.write("        transition: all 0.2s ease;\r\n");
      out.write("        position: relative;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .feature-card::before {\r\n");
      out.write("        content: '';\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 0;\r\n");
      out.write("        left: 0;\r\n");
      out.write("        right: 0;\r\n");
      out.write("        height: 4px;\r\n");
      out.write("        background: linear-gradient(90deg, #2C7744, #5CA564);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .feature-card:hover {\r\n");
      out.write("        transform: translateY(-2px);\r\n");
      out.write("        box-shadow: 0 8px 25px rgba(0, 0, 0, 0.12);\r\n");
      out.write("        border-color: #2C7744;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .feature-icon {\r\n");
      out.write("        font-size: 48px;\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("        display: block;\r\n");
      out.write("        opacity: 0.9;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .feature-title {\r\n");
      out.write("        font-size: 20px;\r\n");
      out.write("        font-weight: 700;\r\n");
      out.write("        color: #2c3e50;\r\n");
      out.write("        margin-bottom: 12px;\r\n");
      out.write("        line-height: 1.3;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .feature-description {\r\n");
      out.write("        color: #6c757d;\r\n");
      out.write("        margin-bottom: 24px;\r\n");
      out.write("        line-height: 1.6;\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .feature-link {\r\n");
      out.write("        background: linear-gradient(135deg, #2C7744 0%, #5CA564 100%);\r\n");
      out.write("        color: white;\r\n");
      out.write("        padding: 14px 28px;\r\n");
      out.write("        border-radius: 8px;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("        transition: all 0.2s ease;\r\n");
      out.write("        border: none;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("        box-shadow: 0 2px 8px rgba(44, 119, 68, 0.2);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .feature-link:hover {\r\n");
      out.write("        transform: translateY(-1px);\r\n");
      out.write("        box-shadow: 0 4px 15px rgba(44, 119, 68, 0.3);\r\n");
      out.write("        color: white;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* レスポンシブ対応の強化 */\r\n");
      out.write("    @media (max-width: 768px) {\r\n");
      out.write("        .dashboard-container {\r\n");
      out.write("            padding: 16px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .dashboard-header {\r\n");
      out.write("            padding: 24px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .user-info {\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .user-details h2 {\r\n");
      out.write("            font-size: 24px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .dashboard-main {\r\n");
      out.write("            grid-template-columns: 1fr;\r\n");
      out.write("            gap: 16px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .feature-card {\r\n");
      out.write("            padding: 24px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .feature-title {\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @media (max-width: 480px) {\r\n");
      out.write("        .dashboard-container {\r\n");
      out.write("            padding: 12px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .dashboard-header {\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .user-avatar {\r\n");
      out.write("            width: 56px;\r\n");
      out.write("            height: 56px;\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .user-details h2 {\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .feature-card {\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* アクセシビリティの向上 */\r\n");
      out.write("    .feature-link:focus {\r\n");
      out.write("        outline: 3px solid #2C7744;\r\n");
      out.write("        outline-offset: 2px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .feature-card:focus-within {\r\n");
      out.write("        outline: 2px solid #2C7744;\r\n");
      out.write("        outline-offset: 2px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* 高コントラストモード対応 */\r\n");
      out.write("    @media (prefers-contrast: high) {\r\n");
      out.write("        .feature-card {\r\n");
      out.write("            border: 2px solid #2c3e50;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .feature-link {\r\n");
      out.write("            border: 2px solid #2c3e50;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ダークモード対応 */\r\n");
      out.write("    @media (prefers-color-scheme: dark) {\r\n");
      out.write("        .dashboard-page {\r\n");
      out.write("            background: #1a1a1a;\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .dashboard-container {\r\n");
      out.write("            background: #2d2d2d;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .feature-card {\r\n");
      out.write("            background: #3d3d3d;\r\n");
      out.write("            border-color: #4d4d4d;\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .feature-title {\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .feature-description {\r\n");
      out.write("            color: #cccccc;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* アニメーションの最適化 */\r\n");
      out.write("    .feature-card {\r\n");
      out.write("        animation: fadeInUp 0.4s ease forwards;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @keyframes fadeInUp {\r\n");
      out.write("        from {\r\n");
      out.write("            opacity: 0;\r\n");
      out.write("            transform: translateY(20px);\r\n");
      out.write("        }\r\n");
      out.write("        to {\r\n");
      out.write("            opacity: 1;\r\n");
      out.write("            transform: translateY(0);\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ローディング画面の最適化 */\r\n");
      out.write("    .dashboard-loading {\r\n");
      out.write("        position: fixed;\r\n");
      out.write("        top: 0;\r\n");
      out.write("        left: 0;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        background: rgba(44, 119, 68, 0.95);\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        z-index: 9999;\r\n");
      out.write("        opacity: 1;\r\n");
      out.write("        transition: opacity 0.3s ease-in-out;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .dashboard-loading.fade-out {\r\n");
      out.write("        opacity: 0;\r\n");
      out.write("        pointer-events: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .dashboard-loading-container {\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        color: white;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .dashboard-loading-spinner {\r\n");
      out.write("        width: 60px;\r\n");
      out.write("        height: 60px;\r\n");
      out.write("        border: 4px solid rgba(255, 255, 255, 0.2);\r\n");
      out.write("        border-top: 4px solid white;\r\n");
      out.write("        border-radius: 50%;\r\n");
      out.write("        animation: spin 1s linear infinite;\r\n");
      out.write("        margin: 0 auto 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .dashboard-loading-text {\r\n");
      out.write("        font-size: 18px;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        margin-bottom: 8px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .dashboard-loading-subtext {\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        opacity: 0.8;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @keyframes spin {\r\n");
      out.write("        0% { transform: rotate(0deg); }\r\n");
      out.write("        100% { transform: rotate(360deg); }\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"dashboard-page\">\r\n");
 
  String username = (String) session.getAttribute("username"); 
  String role = (String) session.getAttribute("role"); 
  
  // 権限名を日本語に変換
  String roleDisplay = "";
  switch(role) {
    case "teacher": roleDisplay = "教員"; break;
    case "headmaster": roleDisplay = "教務部長・校長"; break;
    case "egd": roleDisplay = "就職指導部"; break;
    case "admin": roleDisplay = "システム管理者"; break;
    case "student": roleDisplay = "学生"; break;
    default: roleDisplay = role; break;
  }

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- ダッシュボードローディング画面 -->\r\n");
      out.write("<div id=\"dashboardLoading\" class=\"dashboard-loading\">\r\n");
      out.write("    <div class=\"dashboard-loading-container\">\r\n");
      out.write("        <div class=\"dashboard-loading-spinner\"></div>\r\n");
      out.write("        <div class=\"dashboard-loading-text\">ダッシュボードを読み込み中...</div>\r\n");
      out.write("        <div class=\"dashboard-loading-subtext\">しばらくお待ちください</div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"container\">\r\n");
      out.write("    <!--▼▼▼▼▼ここから「ヘッダー」-->\r\n");
      out.write("    <header>\r\n");
      out.write("        <h1 id=\"logo\"><a href=\"javascript:void(0);\" onclick=\"location.reload();\"><img src=\"images/logo.png\" alt=\"jms\"></a></h1>\r\n");
      out.write("        <nav>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"javascript:void(0);\" onclick=\"location.reload();\">ホーム</a></li>\r\n");
      out.write("                <!-- 権限に応じた機能リンク -->\r\n");
      out.write("                ");
 if ("teacher".equals(role) || "headmaster".equals(role) || "admin".equals(role)) { 
      out.write("\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/StatusServlet?view=studentManagement\">学生管理</a></li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                ");
 if ("egd".equals(role) || "admin".equals(role)) { 
      out.write("\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/StatusServlet?view=CompanyManagement\">企業管理</a></li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                ");
 if ("teacher".equals(role) || "headmaster".equals(role) || "egd".equals(role) || "admin".equals(role) || "student".equals(role)) { 
      out.write("\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/StatusServlet?view=jobHunting\">就職管理</a></li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                ");
 if ("teacher".equals(role) || "headmaster".equals(role) || "egd".equals(role) || "admin".equals(role)) { 
      out.write("\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/StatusServlet?view=applicantList\">受験者一覧</a></li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                ");
 if ("admin".equals(role)) { 
      out.write("\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/StatusServlet?view=adminDatabase.jsp\">システム管理</a></li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                <li><a href=\"extension.html\">お問い合わせ</a></li>\r\n");
      out.write("                ");
 if (username != null) { 
      out.write("\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/LogoutServlet\">ログアウト</a></li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("    <!--▲▲▲▲▲ここまで「ヘッダー」-->\r\n");
      out.write("\r\n");
      out.write("    <main>\r\n");
      out.write("        <!--▼▼▼▼▼ここから「ダッシュボードメイン」-->\r\n");
      out.write("        <section class=\"bg1 bg-pattern1\" role=\"main\" aria-label=\"ダッシュボードメイン\">\r\n");
      out.write("            <div class=\"dashboard-container\">\r\n");
      out.write("                <!-- ダッシュボードヘッダー -->\r\n");
      out.write("                <div class=\"dashboard-header\">\r\n");
      out.write("                    <div class=\"user-info\">\r\n");
      out.write("                        <div class=\"user-welcome\">\r\n");
      out.write("                            <div class=\"user-avatar\">\r\n");
      out.write("                                ");
      out.print( username != null ? username.charAt(0) : "U" );
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"user-details\">\r\n");
      out.write("                                <h2>こんにちは、");
      out.print( username != null ? username : "ゲスト" );
      out.write("さん</h2>\r\n");
      out.write("                                <span class=\"role-badge\">");
      out.print( roleDisplay );
      out.write("</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        ");
 if (username != null) { 
      out.write("\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/LogoutServlet\" class=\"logout-btn\">ログアウト</a>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- メインコンテンツ -->\r\n");
      out.write("                <div class=\"dashboard-main\" role=\"region\" aria-label=\"機能メニュー\">\r\n");
      out.write("                    \r\n");
      out.write("                    <!-- 学生管理機能 -->\r\n");
      out.write("                    ");
 if ("teacher".equals(role) || "headmaster".equals(role) || "admin".equals(role)) { 
      out.write("\r\n");
      out.write("                        <div class=\"feature-card\">\r\n");
      out.write("                            <span class=\"feature-icon\">📚</span>\r\n");
      out.write("                            <h3 class=\"feature-title\">学生管理</h3>\r\n");
      out.write("                            <p class=\"feature-description\">\r\n");
      out.write("                                学生の情報を管理し、就職活動の進捗を把握できます。\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/StatusServlet?view=studentManagement\" class=\"feature-link\">\r\n");
      out.write("                                学生管理画面を開く\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <!-- 企業管理機能 -->\r\n");
      out.write("                    ");
 if ("egd".equals(role) || "admin".equals(role)) { 
      out.write("\r\n");
      out.write("                        <div class=\"feature-card\">\r\n");
      out.write("                            <span class=\"feature-icon\">🏢</span>\r\n");
      out.write("                            <h3 class=\"feature-title\">企業管理</h3>\r\n");
      out.write("                            <p class=\"feature-description\">\r\n");
      out.write("                                企業情報の登録・編集と求人情報の管理を行います。\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/StatusServlet?view=CompanyManagement\" class=\"feature-link\">\r\n");
      out.write("                                企業管理画面を開く\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <!-- 就職管理機能 -->\r\n");
      out.write("                    ");
 if ("teacher".equals(role) || "headmaster".equals(role) || "egd".equals(role) || "admin".equals(role) || "student".equals(role)) { 
      out.write("\r\n");
      out.write("                        <div class=\"feature-card\">\r\n");
      out.write("                            <span class=\"feature-icon\">📄</span>\r\n");
      out.write("                            <h3 class=\"feature-title\">就職管理</h3>\r\n");
      out.write("                            <p class=\"feature-description\">\r\n");
      out.write("                                就職活動の進捗管理と選考状況の記録を行います。\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/StatusServlet?view=jobHunting\" class=\"feature-link\">\r\n");
      out.write("                                就職管理画面を開く\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <!-- 受験者一覧機能 -->\r\n");
      out.write("                    ");
 if ("teacher".equals(role) || "headmaster".equals(role) || "egd".equals(role) || "admin".equals(role)) { 
      out.write("\r\n");
      out.write("                        <div class=\"feature-card\">\r\n");
      out.write("                            <span class=\"feature-icon\">📊</span>\r\n");
      out.write("                            <h3 class=\"feature-title\">受験者一覧</h3>\r\n");
      out.write("                            <p class=\"feature-description\">\r\n");
      out.write("                                企業の選考に応募した学生の一覧と進捗を確認できます。\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/StatusServlet?view=applicantList\" class=\"feature-link\">\r\n");
      out.write("                                受験者一覧を表示\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <!-- 管理者DB機能 -->\r\n");
      out.write("                    ");
 if ("admin".equals(role)) { 
      out.write("\r\n");
      out.write("                        <div class=\"feature-card\">\r\n");
      out.write("                            <span class=\"feature-icon\">🛠</span>\r\n");
      out.write("                            <h3 class=\"feature-title\">システム管理</h3>\r\n");
      out.write("                            <p class=\"feature-description\">\r\n");
      out.write("                                データベースの管理とシステム設定を行います。\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/StatusServlet?view=adminDatabase.jsp\" class=\"feature-link\">\r\n");
      out.write("                                管理者DBを開く\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <!-- 権限エラー表示 -->\r\n");
      out.write("                    ");
 if (username != null && !("teacher".equals(role) || "headmaster".equals(role) || "egd".equals(role) || "admin".equals(role) || "student".equals(role))) { 
      out.write("\r\n");
      out.write("                        <div class=\"feature-card\" style=\"background: #ffebee; border-left: 4px solid #f44336;\">\r\n");
      out.write("                            <span class=\"feature-icon\">⚠️</span>\r\n");
      out.write("                            <h3 class=\"feature-title\">アクセスエラー</h3>\r\n");
      out.write("                            <p class=\"feature-description\">\r\n");
      out.write("                                現在の権限では利用できる機能がありません。\r\n");
      out.write("                                システム管理者にお問い合わせください。\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!--▲▲▲▲▲ここまで「ダッシュボードメイン」-->\r\n");
      out.write("\r\n");
      out.write("        <!--▼▼▼▼▼ここから「お知らせセクション」-->\r\n");
      out.write("        <section class=\"bg3 bg-pattern3 arrow\">\r\n");
      out.write("            <div class=\"c2\">\r\n");
      out.write("                <div class=\"title\">\r\n");
      out.write("                    <h2>お知らせ<span>News</span></h2>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"text\">\r\n");
      out.write("                    <dl class=\"new\">\r\n");
      out.write("                        <dt>2025/01/20<span>重要</span></dt>\r\n");
      out.write("                        <dd>本年度の就職活動スケジュールが更新されました。2年次の自己分析ワークショップは1月25日に開催されます。詳細は教務部へお問い合わせください。</dd>\r\n");
      out.write("\r\n");
      out.write("                        <dt>2025/01/15<span class=\"icon-bg1\">企業説明会</span></dt>\r\n");
      out.write("                        <dd>県内外の主要企業による説明会が1月25日からスタートします。このアプリで予約が可能ですので、お早めに登録をしてください。</dd>\r\n");
      out.write("\r\n");
      out.write("                        <dt>2025/01/10<span class=\"icon-bg2\">就職対策</span></dt>\r\n");
      out.write("                        <dd>模擬面接セッションの追加開催が決定しました！1月20日から週ごとに行われます。JMSアプリを活用して予約が可能です。</dd>\r\n");
      out.write("\r\n");
      out.write("                        <dt>2025/01/05<span>その他</span></dt>\r\n");
      out.write("                        <dd>今年度の就職活動用アプリの新機能について説明会を実施します。1月30日にオンラインで行いますので、詳細は教務部の通知をご確認ください。</dd>\r\n");
      out.write("\r\n");
      out.write("                        <dt>2025/01/01<span>重要</span></dt>\r\n");
      out.write("                        <dd>内定承諾書の提出期限が近づいています。各自スケジュールを確認し、必要な書類を1月末までに提出してください。</dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!--▲▲▲▲▲ここまで「お知らせセクション」-->\r\n");
      out.write("\r\n");
      out.write("        <!--▼▼▼▼▼ここから「クイックアクセス」-->\r\n");
      out.write("        <section class=\"bg-primary-color\">\r\n");
      out.write("            <h2 class=\"c\">クイックアクセス<span>Quick Access</span></h2>\r\n");
      out.write("            <div class=\"list-c2\">\r\n");
      out.write("                <div class=\"list image1\">\r\n");
      out.write("                    <div class=\"text\">\r\n");
      out.write("                        <h4><span class=\"sub-text\">お問い合わせ</span><span class=\"main-text\">Contact</span></h4>\r\n");
      out.write("                        <p class=\"btn1\"><a href=\"extension.html\">お問い合わせフォーム</a></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"list image2\">\r\n");
      out.write("                    <div class=\"text\">\r\n");
      out.write("                        <h4><span class=\"sub-text\">資料請求</span><span class=\"main-text\">Request</span></h4>\r\n");
      out.write("                        <p class=\"btn1\"><a href=\"extension.html\">資料請求フォーム</a></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!--▲▲▲▲▲ここまで「クイックアクセス」-->\r\n");
      out.write("    </main>\r\n");
      out.write("\r\n");
      out.write("    <!--▼▼▼▼▼ここから「フッター」-->\r\n");
      out.write("    <footer>\r\n");
      out.write("        <div>\r\n");
      out.write("            <p class=\"logo\"><img src=\"images/logo.png\" alt=\"Job Management System\"></p>\r\n");
      out.write("            <ul class=\"icons\">\r\n");
      out.write("                <li><a href=\"#\"><i class=\"fa-brands fa-x-twitter\"></i></a></li>\r\n");
      out.write("                <li><a href=\"#\"><i class=\"fab fa-line\"></i></a></li>\r\n");
      out.write("                <li><a href=\"#\"><i class=\"fab fa-youtube\"></i></a></li>\r\n");
      out.write("                <li><a href=\"#\"><i class=\"fab fa-instagram\"></i></a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <small>Copyright&copy; @ 2025 Job Management System All Rights Reserved.</small>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"javascript:void(0);\" onclick=\"location.reload();\">ホーム</a></li>\r\n");
      out.write("                <!-- 権限に応じた機能リンク -->\r\n");
      out.write("                ");
 if ("teacher".equals(role) || "headmaster".equals(role) || "admin".equals(role)) { 
      out.write("\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/StatusServlet?view=studentManagement\">学生管理</a></li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                ");
 if ("egd".equals(role) || "admin".equals(role)) { 
      out.write("\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/StatusServlet?view=CompanyManagement\">企業管理</a></li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                ");
 if ("teacher".equals(role) || "headmaster".equals(role) || "egd".equals(role) || "admin".equals(role) || "student".equals(role)) { 
      out.write("\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/StatusServlet?view=jobHunting\">就職管理</a></li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                ");
 if ("teacher".equals(role) || "headmaster".equals(role) || "egd".equals(role) || "admin".equals(role)) { 
      out.write("\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/StatusServlet?view=applicantList\">受験者一覧</a></li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                ");
 if ("admin".equals(role)) { 
      out.write("\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/StatusServlet?view=adminDatabase.jsp\">システム管理</a></li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                <li><a href=\"extension.html\">お問い合わせ</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <!--▲▲▲▲▲ここまで「フッター」-->\r\n");
      out.write("\r\n");
      out.write("    <!--▼▼最下部-->\r\n");
      out.write("    <span class=\"pr\"><a href=\"\" target=\"_blank\">@ 2025 Job Management System</a></span>\r\n");
      out.write("    <!--▲▲ここまで最下部-->\r\n");
      out.write("</div>\r\n");
      out.write("<!--/#container-->\r\n");
      out.write("\r\n");
      out.write("<!--開閉ボタン（ハンバーガーアイコン）-->\r\n");
      out.write("<div id=\"menubar_hdr\">\r\n");
      out.write("    <span></span><span></span><span></span>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!--開閉ブロック-->\r\n");
      out.write("<div id=\"menubar\">\r\n");
      out.write("    <p class=\"logo\"><img src=\"images/logo.png\" alt=\"Job Management System\"></p>\r\n");
      out.write("    <nav>\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li><a href=\"javascript:void(0);\" onclick=\"location.reload();\">ホーム</a></li>\r\n");
      out.write("            <!-- 権限に応じた機能リンク -->\r\n");
      out.write("            ");
 if ("teacher".equals(role) || "headmaster".equals(role) || "admin".equals(role)) { 
      out.write("\r\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/StatusServlet?view=studentManagement\">学生管理</a></li>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            ");
 if ("egd".equals(role) || "admin".equals(role)) { 
      out.write("\r\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/StatusServlet?view=CompanyManagement\">企業管理</a></li>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            ");
 if ("teacher".equals(role) || "headmaster".equals(role) || "egd".equals(role) || "admin".equals(role) || "student".equals(role)) { 
      out.write("\r\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/StatusServlet?view=jobHunting\">就職管理</a></li>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            ");
 if ("teacher".equals(role) || "headmaster".equals(role) || "egd".equals(role) || "admin".equals(role)) { 
      out.write("\r\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/StatusServlet?view=applicantList\">受験者一覧</a></li>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            ");
 if ("admin".equals(role)) { 
      out.write("\r\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/StatusServlet?view=adminDatabase.jsp\">システム管理</a></li>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            <li><a href=\"extension.html\">お問い合わせ</a></li>\r\n");
      out.write("            ");
 if (username != null) { 
      out.write("\r\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/LogoutServlet\">ログアウト</a></li>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("</div>\r\n");
      out.write("<!--/#menubar-->\r\n");
      out.write("\r\n");
      out.write("<!--jQueryの読み込み-->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("<!--パララックス（inview）-->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/protonet-jquery.inview/1.1.2/jquery.inview.min.js\"></script>\r\n");
      out.write("<script src=\"js/jquery.inview_set.js\"></script>\r\n");
      out.write("<!--このテンプレート専用のスクリプト-->\r\n");
      out.write("<script src=\"js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("// 最適化されたダッシュボードローディング制御\r\n");
      out.write("document.addEventListener('DOMContentLoaded', () => {\r\n");
      out.write("    // ローディング時間を0.5秒に短縮\r\n");
      out.write("    setTimeout(() => {\r\n");
      out.write("        const loadingElement = document.getElementById('dashboardLoading');\r\n");
      out.write("        if (loadingElement) {\r\n");
      out.write("            loadingElement.classList.add('fade-out');\r\n");
      out.write("            // フェードアウト完了後に要素を削除\r\n");
      out.write("            setTimeout(() => {\r\n");
      out.write("                loadingElement.remove();\r\n");
      out.write("            }, 300);\r\n");
      out.write("        }\r\n");
      out.write("    }, 500);\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("// アクセシビリティの向上\r\n");
      out.write("document.addEventListener('DOMContentLoaded', () => {\r\n");
      out.write("    // キーボードナビゲーションの改善\r\n");
      out.write("    const featureLinks = document.querySelectorAll('.feature-link');\r\n");
      out.write("    featureLinks.forEach(link => {\r\n");
      out.write("        link.addEventListener('keydown', (e) => {\r\n");
      out.write("            if (e.key === 'Enter' || e.key === ' ') {\r\n");
      out.write("                e.preventDefault();\r\n");
      out.write("                link.click();\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    // フォーカス管理の改善\r\n");
      out.write("    const focusableElements = document.querySelectorAll('a, button, input, select, textarea, [tabindex]:not([tabindex=\"-1\"])');\r\n");
      out.write("    focusableElements.forEach(element => {\r\n");
      out.write("        element.addEventListener('focus', () => {\r\n");
      out.write("            element.style.outline = '2px solid #2C7744';\r\n");
      out.write("            element.style.outlineOffset = '2px';\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        element.addEventListener('blur', () => {\r\n");
      out.write("            element.style.outline = '';\r\n");
      out.write("            element.style.outlineOffset = '';\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("// パフォーマンス最適化\r\n");
      out.write("window.addEventListener('load', () => {\r\n");
      out.write("    // 画像の遅延読み込み\r\n");
      out.write("    const images = document.querySelectorAll('img[data-src]');\r\n");
      out.write("    const imageObserver = new IntersectionObserver((entries, observer) => {\r\n");
      out.write("        entries.forEach(entry => {\r\n");
      out.write("            if (entry.isIntersecting) {\r\n");
      out.write("                const img = entry.target;\r\n");
      out.write("                img.src = img.dataset.src;\r\n");
      out.write("                img.removeAttribute('data-src');\r\n");
      out.write("                observer.unobserve(img);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    images.forEach(img => imageObserver.observe(img));\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
