/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.28
 * Generated at: 2025-07-02 05:49:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class StudentManagement_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPではGET、POST、またはHEADのみが許可されます。 JasperはOPTIONSも許可しています。");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--*\r\n");
      out.write("：：：色のテーマは緑：：：\r\n");
      out.write("学生管理画面\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("**********\r\n");
      out.write("\r\n");
      out.write("<!--* 画面：学生管理画面\r\n");
      out.write("        	\r\n");
      out.write("許可されている権限：\r\n");
      out.write("・教員：teacher\r\n");
      out.write("・校長・教務部長：headmaster\r\n");
      out.write("・システム管理者：admin\r\n");
      out.write(" \r\n");
      out.write("▼▼▼▼\r\n");
      out.write("*-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--確認まだ-->\r\n");
      out.write("\r\n");
      out.write("<!--KCS_JMS_PROJECT-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 学生管理画面用 -->\r\n");
      out.write("\r\n");
      out.write("<!-- バックエンドとの接続のやり取りがあるためいったん放置 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--▼▼▼▼▼スコープから取得する情報　これをもとに判定をしていく -->\r\n");
 
  String username = (String) session.getAttribute("username"); 
  String role     = (String) session.getAttribute("role"); 
  
  // デバッグ用：セッション情報をコンソールに出力
  System.out.println("StudentManagement.jsp - username: " + username);
  System.out.println("StudentManagement.jsp - role: " + role);
  
  // nullチェック
  if (username == null) {
    username = "ゲスト";
  }
  if (role == null) {
    role = "guest";
  }
  
  // リクエストスコープからプルダウン用データを取得
  java.util.List<String> classList = (java.util.List<String>) request.getAttribute("classList");
  java.util.List<String> enrollmentStatusList = (java.util.List<String>) request.getAttribute("enrollmentStatusList");
  java.util.List<String> assistanceList = (java.util.List<String>) request.getAttribute("assistanceList");
  java.util.List<String> firstChoiceIndustryList = (java.util.List<String>) request.getAttribute("firstChoiceIndustryList");
  java.util.List<Integer> graduationYearList = (java.util.List<Integer>) request.getAttribute("graduationYearList");
  
  // エラーメッセージを取得
  String errorMessage = (String) request.getAttribute("errorMessage");

      out.write("\r\n");
      out.write("<!--▲▲▲▲▲-->\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ja\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>JMSアプリ - 学生管理</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta name=\"description\" content=\"本アプリは就職対策アプリです。\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    /* システム上見やすさを追求した学生管理画面デザイン */\r\n");
      out.write("    \r\n");
      out.write("    /* 全体の設定 */\r\n");
      out.write("    .student-management-page {\r\n");
      out.write("        background: #f8f9fa;\r\n");
      out.write("        color: #2c3e50;\r\n");
      out.write("        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("        line-height: 1.6;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .student-management-container {\r\n");
      out.write("        max-width: 1400px;\r\n");
      out.write("        margin: 0 auto;\r\n");
      out.write("        padding: 24px;\r\n");
      out.write("        min-height: 100vh;\r\n");
      out.write("        background: #ffffff;\r\n");
      out.write("        box-shadow: 0 0 20px rgba(0, 0, 0, 0.05);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ページヘッダー - 視認性向上 */\r\n");
      out.write("    .page-header {\r\n");
      out.write("        background: linear-gradient(135deg, #2C7744 0%, #5CA564 100%);\r\n");
      out.write("        border-radius: 12px;\r\n");
      out.write("        padding: 32px;\r\n");
      out.write("        margin-bottom: 32px;\r\n");
      out.write("        box-shadow: 0 4px 20px rgba(44, 119, 68, 0.15);\r\n");
      out.write("        color: #000000;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        position: relative;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .page-title {\r\n");
      out.write("        font-size: 32px;\r\n");
      out.write("        color: #000000;\r\n");
      out.write("        margin-bottom: 12px;\r\n");
      out.write("        font-weight: 700;\r\n");
      out.write("        text-shadow: 0 1px 2px rgba(255, 255, 255, 0.3);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .page-subtitle {\r\n");
      out.write("        font-size: 18px;\r\n");
      out.write("        color: #000000;\r\n");
      out.write("        margin-bottom: 24px;\r\n");
      out.write("        line-height: 1.6;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .breadcrumb {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        gap: 12px;\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        color: #000000;\r\n");
      out.write("        margin-top: 16px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .breadcrumb a {\r\n");
      out.write("        color: #000000;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        transition: all 0.2s ease;\r\n");
      out.write("        padding: 6px 12px;\r\n");
      out.write("        border-radius: 6px;\r\n");
      out.write("        background: rgba(255, 255, 255, 0.3);\r\n");
      out.write("        border: 1px solid rgba(255, 255, 255, 0.4);\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .breadcrumb a:hover {\r\n");
      out.write("        background: rgba(255, 255, 255, 0.5);\r\n");
      out.write("        transform: translateY(-1px);\r\n");
      out.write("        color: #000000;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .breadcrumb .separator {\r\n");
      out.write("        color: #000000;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* クイックアクション - 視認性と操作性の向上 */\r\n");
      out.write("    .quick-actions {\r\n");
      out.write("        background: white;\r\n");
      out.write("        border-radius: 12px;\r\n");
      out.write("        padding: 32px;\r\n");
      out.write("        box-shadow: 0 2px 12px rgba(0, 0, 0, 0.08);\r\n");
      out.write("        border: 1px solid #e9ecef;\r\n");
      out.write("        margin-bottom: 32px;\r\n");
      out.write("        position: relative;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .quick-actions::before {\r\n");
      out.write("        content: '';\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 0;\r\n");
      out.write("        left: 0;\r\n");
      out.write("        right: 0;\r\n");
      out.write("        height: 4px;\r\n");
      out.write("        background: linear-gradient(90deg, #2C7744, #5CA564);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .quick-actions h3 {\r\n");
      out.write("        font-size: 20px;\r\n");
      out.write("        color: #2c3e50;\r\n");
      out.write("        margin-bottom: 24px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        font-weight: 700;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .action-buttons {\r\n");
      out.write("        display: grid;\r\n");
      out.write("        grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));\r\n");
      out.write("        gap: 16px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .action-btn {\r\n");
      out.write("        background: linear-gradient(135deg, #2C7744 0%, #5CA564 100%);\r\n");
      out.write("        color: white;\r\n");
      out.write("        padding: 16px 24px;\r\n");
      out.write("        border-radius: 8px;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        gap: 10px;\r\n");
      out.write("        transition: all 0.2s ease;\r\n");
      out.write("        border: none;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("        box-shadow: 0 2px 8px rgba(44, 119, 68, 0.2);\r\n");
      out.write("        position: relative;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .action-btn:hover {\r\n");
      out.write("        transform: translateY(-1px);\r\n");
      out.write("        box-shadow: 0 4px 15px rgba(44, 119, 68, 0.3);\r\n");
      out.write("        color: white;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .action-btn.secondary {\r\n");
      out.write("        background: linear-gradient(135deg, #6c757d 0%, #495057 100%);\r\n");
      out.write("        box-shadow: 0 2px 8px rgba(108, 117, 125, 0.2);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .action-btn.secondary:hover {\r\n");
      out.write("        box-shadow: 0 4px 15px rgba(108, 117, 125, 0.3);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* メインコンテンツ - 情報階層の改善 */\r\n");
      out.write("    .management-main {\r\n");
      out.write("        display: grid;\r\n");
      out.write("        grid-template-columns: repeat(auto-fit, minmax(400px, 1fr));\r\n");
      out.write("        gap: 24px;\r\n");
      out.write("        margin-bottom: 32px;\r\n");
      out.write("        max-width: 1200px;\r\n");
      out.write("        margin-left: auto;\r\n");
      out.write("        margin-right: auto;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* 機能カード - 視認性と操作性の向上 */\r\n");
      out.write("    .management-card {\r\n");
      out.write("        background: white;\r\n");
      out.write("        border-radius: 12px;\r\n");
      out.write("        padding: 32px;\r\n");
      out.write("        box-shadow: 0 2px 12px rgba(0, 0, 0, 0.08);\r\n");
      out.write("        border: 1px solid #e9ecef;\r\n");
      out.write("        transition: all 0.2s ease;\r\n");
      out.write("        position: relative;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .management-card::before {\r\n");
      out.write("        content: '';\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 0;\r\n");
      out.write("        left: 0;\r\n");
      out.write("        right: 0;\r\n");
      out.write("        height: 4px;\r\n");
      out.write("        background: linear-gradient(90deg, #2C7744, #5CA564);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .management-card:hover {\r\n");
      out.write("        transform: translateY(-2px);\r\n");
      out.write("        box-shadow: 0 8px 25px rgba(0, 0, 0, 0.12);\r\n");
      out.write("        border-color: #2C7744;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card-icon {\r\n");
      out.write("        font-size: 48px;\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("        display: block;\r\n");
      out.write("        opacity: 0.9;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card-title {\r\n");
      out.write("        font-size: 20px;\r\n");
      out.write("        font-weight: 700;\r\n");
      out.write("        color: #2c3e50;\r\n");
      out.write("        margin-bottom: 12px;\r\n");
      out.write("        line-height: 1.3;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card-description {\r\n");
      out.write("        color: #6c757d;\r\n");
      out.write("        margin-bottom: 24px;\r\n");
      out.write("        line-height: 1.6;\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card-stats {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: space-around;\r\n");
      out.write("        margin-bottom: 24px;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        background: linear-gradient(135deg, rgba(44, 119, 68, 0.05), rgba(92, 165, 100, 0.05));\r\n");
      out.write("        border-radius: 8px;\r\n");
      out.write("        border: 1px solid rgba(44, 119, 68, 0.1);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .stat-item {\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        position: relative;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .stat-item:not(:last-child)::after {\r\n");
      out.write("        content: '';\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        right: -50%;\r\n");
      out.write("        top: 50%;\r\n");
      out.write("        transform: translateY(-50%);\r\n");
      out.write("        width: 1px;\r\n");
      out.write("        height: 30px;\r\n");
      out.write("        background: linear-gradient(to bottom, transparent, rgba(44, 119, 68, 0.3), transparent);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .stat-number {\r\n");
      out.write("        font-size: 24px;\r\n");
      out.write("        font-weight: 700;\r\n");
      out.write("        color: #2C7744;\r\n");
      out.write("        display: block;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .stat-label {\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        color: #6c757d;\r\n");
      out.write("        margin-top: 6px;\r\n");
      out.write("        font-weight: 500;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card-link {\r\n");
      out.write("        background: linear-gradient(135deg, #2C7744 0%, #5CA564 100%);\r\n");
      out.write("        color: white;\r\n");
      out.write("        padding: 14px 28px;\r\n");
      out.write("        border-radius: 8px;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("        transition: all 0.2s ease;\r\n");
      out.write("        border: none;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("        box-shadow: 0 2px 8px rgba(44, 119, 68, 0.2);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card-link:hover {\r\n");
      out.write("        transform: translateY(-1px);\r\n");
      out.write("        box-shadow: 0 4px 15px rgba(44, 119, 68, 0.3);\r\n");
      out.write("        color: white;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* レスポンシブ対応の強化 */\r\n");
      out.write("    @media (max-width: 768px) {\r\n");
      out.write("        .student-management-container {\r\n");
      out.write("            padding: 16px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .page-header {\r\n");
      out.write("            padding: 24px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .page-title {\r\n");
      out.write("            font-size: 24px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .page-subtitle {\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .management-main {\r\n");
      out.write("            grid-template-columns: 1fr;\r\n");
      out.write("            gap: 16px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .action-buttons {\r\n");
      out.write("            grid-template-columns: 1fr;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .quick-actions {\r\n");
      out.write("            padding: 24px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .management-card {\r\n");
      out.write("            padding: 24px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .card-stats {\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            gap: 12px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .stat-item:not(:last-child)::after {\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @media (max-width: 480px) {\r\n");
      out.write("        .student-management-container {\r\n");
      out.write("            padding: 12px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .page-header {\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .page-title {\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .quick-actions {\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .management-card {\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .card-title {\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* アクセシビリティの向上 */\r\n");
      out.write("    .action-btn:focus,\r\n");
      out.write("    .card-link:focus {\r\n");
      out.write("        outline: 3px solid #2C7744;\r\n");
      out.write("        outline-offset: 2px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .management-card:focus-within {\r\n");
      out.write("        outline: 2px solid #2C7744;\r\n");
      out.write("        outline-offset: 2px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* 高コントラストモード対応 */\r\n");
      out.write("    @media (prefers-contrast: high) {\r\n");
      out.write("        .management-card {\r\n");
      out.write("            border: 2px solid #2c3e50;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .action-btn,\r\n");
      out.write("        .card-link {\r\n");
      out.write("            border: 2px solid #2c3e50;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ダークモード対応 */\r\n");
      out.write("    @media (prefers-color-scheme: dark) {\r\n");
      out.write("        .student-management-page {\r\n");
      out.write("            background: #1a1a1a;\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .student-management-container {\r\n");
      out.write("            background: #2d2d2d;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .quick-actions,\r\n");
      out.write("        .management-card {\r\n");
      out.write("            background: #3d3d3d;\r\n");
      out.write("            border-color: #4d4d4d;\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .card-title {\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .card-description {\r\n");
      out.write("            color: #cccccc;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* アニメーションの最適化 */\r\n");
      out.write("    .page-header,\r\n");
      out.write("    .quick-actions,\r\n");
      out.write("    .management-card {\r\n");
      out.write("        animation: fadeInUp 0.4s ease forwards;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @keyframes fadeInUp {\r\n");
      out.write("        from {\r\n");
      out.write("            opacity: 0;\r\n");
      out.write("            transform: translateY(20px);\r\n");
      out.write("        }\r\n");
      out.write("        to {\r\n");
      out.write("            opacity: 1;\r\n");
      out.write("            transform: translateY(0);\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ダッシュボード用ヘッダー調整 */\r\n");
      out.write("    .student-management-page header {\r\n");
      out.write("        position: relative;\r\n");
      out.write("        background: rgba(255, 255, 255, 0.95);\r\n");
      out.write("        backdrop-filter: blur(10px);\r\n");
      out.write("        border-bottom: 1px solid rgba(0, 0, 0, 0.1);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .student-management-page #mainimg {\r\n");
      out.write("        display: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .student-management-page main {\r\n");
      out.write("        margin-top: 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* テキストスライドショー用の調整 */\r\n");
      out.write("    .student-management-page .text-slide-wrapper {\r\n");
      out.write("        margin-top: 0;\r\n");
      out.write("        margin-bottom: 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .student-management-page .text-slide {\r\n");
      out.write("        font-size: 8vw;\r\n");
      out.write("        opacity: 0.08;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"student-management-page\">\r\n");
 
  // 権限名を日本語に変換
  String roleDisplay = "";
  switch(role) {
    case "teacher": roleDisplay = "教員"; break;
    case "headmaster": roleDisplay = "教務部長・校長"; break;
    case "egd": roleDisplay = "就職指導部"; break;
    case "admin": roleDisplay = "システム管理者"; break;
    case "student": roleDisplay = "学生"; break;
    default: roleDisplay = role; break;
  }

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"container\">\r\n");
      out.write("    <!--▼▼▼▼▼ここから「ヘッダー」-->\r\n");
      out.write("    <header>\r\n");
      out.write("        <h1 id=\"logo\"><a href=\"javascript:void(0);\" onclick=\"location.reload();\"><img src=\"images/logo.png\" alt=\"jms\"></a></h1>\r\n");
      out.write("        <nav>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"javascript:void(0);\" onclick=\"location.reload();\">ホーム</a></li>\r\n");
      out.write("                <!-- 権限に応じた機能リンク -->\r\n");
      out.write("                ");
 if ("teacher".equals(role) || "headmaster".equals(role) || "admin".equals(role)) { 
      out.write("\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/StatusServlet?view=studentManagement\">学生管理</a></li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                ");
 if ("egd".equals(role) || "admin".equals(role)) { 
      out.write("\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/StatusServlet?view=CompanyManagement\">企業管理</a></li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                ");
 if ("teacher".equals(role) || "headmaster".equals(role) || "egd".equals(role) || "admin".equals(role) || "student".equals(role)) { 
      out.write("\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/StatusServlet?view=jobHunting\">就職管理</a></li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                ");
 if ("teacher".equals(role) || "headmaster".equals(role) || "egd".equals(role) || "admin".equals(role)) { 
      out.write("\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/StatusServlet?view=applicantList\">受験者一覧</a></li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                ");
 if ("admin".equals(role)) { 
      out.write("\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/StatusServlet?view=adminDatabase.jsp\">システム管理</a></li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                <li><a href=\"extension.html\">お問い合わせ</a></li>\r\n");
      out.write("                ");
 if (username != null) { 
      out.write("\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/LogoutServlet\">ログアウト</a></li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("    <!--▲▲▲▲▲ここまで「ヘッダー」-->\r\n");
      out.write("\r\n");
      out.write("    <main>\r\n");
      out.write("        <div class=\"student-management-container\">\r\n");
      out.write("            <!-- ページヘッダー -->\r\n");
      out.write("            <header class=\"page-header\" role=\"banner\">\r\n");
      out.write("                <h1 class=\"page-title\">学生管理</h1>\r\n");
      out.write("                <p class=\"page-subtitle\">学生情報の管理と就職活動の進捗を把握できます</p>\r\n");
      out.write("                <nav class=\"breadcrumb\" aria-label=\"パンくずリスト\">\r\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/StatusServlet?view=DashBoard\">ダッシュボード</a>\r\n");
      out.write("                    <span class=\"separator\" aria-hidden=\"true\">/</span>\r\n");
      out.write("                    <span>学生管理</span>\r\n");
      out.write("                </nav>\r\n");
      out.write("            </header>\r\n");
      out.write("\r\n");
      out.write("            <!-- メッセージ表示 -->\r\n");
      out.write("            ");
 if (request.getAttribute("successMessage") != null) { 
      out.write("\r\n");
      out.write("                <div class=\"message success-message\" style=\"background: #d4edda; color: #155724; border: 1px solid #c3e6cb; border-radius: 8px; padding: 16px; margin-bottom: 24px; text-align: center; font-weight: 600;\">\r\n");
      out.write("                    ✅ ");
      out.print( request.getAttribute("successMessage") );
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            ");
 if (request.getAttribute("errorMessage") != null) { 
      out.write("\r\n");
      out.write("                <div class=\"message error-message\" style=\"background: #f8d7da; color: #721c24; border: 1px solid #f5c6cb; border-radius: 8px; padding: 16px; margin-bottom: 24px; text-align: center; font-weight: 600;\">\r\n");
      out.write("                    ❌ ");
      out.print( request.getAttribute("errorMessage") );
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!-- 操作一覧 -->\r\n");
      out.write("            <section class=\"quick-actions\" role=\"region\" aria-label=\"操作一覧\">\r\n");
      out.write("                <h2>🚀 操作一覧</h2>\r\n");
      out.write("                <div class=\"action-buttons\">\r\n");
      out.write("                    <a href=\"StudentServlet\" class=\"action-btn\" aria-label=\"学生一覧を表示\">\r\n");
      out.write("                        <i class=\"fas fa-list\" aria-hidden=\"true\"></i>学生一覧を表示\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"StatusServlet?status=createStudent\" class=\"action-btn\" aria-label=\"新規学生登録\">\r\n");
      out.write("                        <i class=\"fas fa-plus\" aria-hidden=\"true\"></i>新規学生登録\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"StatusServlet?view=studentSearch\" class=\"action-btn secondary\" aria-label=\"学生検索\">\r\n");
      out.write("                        <i class=\"fas fa-search\" aria-hidden=\"true\"></i>学生検索\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <a href=\"StatusServlet?view=studentExport\" class=\"action-btn secondary\" aria-label=\"データエクスポート\">\r\n");
      out.write("                        <i class=\"fas fa-download\" aria-hidden=\"true\"></i>データエクスポート\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </section>\r\n");
      out.write("\r\n");
      out.write("            <!-- メインコンテンツ -->\r\n");
      out.write("            <section class=\"management-main\" role=\"region\" aria-label=\"管理機能\">\r\n");
      out.write("                \r\n");
      out.write("                <!-- 学生一覧管理 -->\r\n");
      out.write("                <article class=\"management-card\" role=\"article\">\r\n");
      out.write("                    <span class=\"card-icon\" aria-hidden=\"true\">📋</span>\r\n");
      out.write("                    <h3 class=\"card-title\">学生一覧管理</h3>\r\n");
      out.write("                    <p class=\"card-description\">\r\n");
      out.write("                        登録されている学生の一覧を表示し、詳細情報の確認や編集を行えます。\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <div class=\"card-stats\" role=\"group\" aria-label=\"学生統計\">\r\n");
      out.write("                        <div class=\"stat-item\">\r\n");
      out.write("                            <span class=\"stat-number\">150</span>\r\n");
      out.write("                            <span class=\"stat-label\">総学生数</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"stat-item\">\r\n");
      out.write("                            <span class=\"stat-number\">45</span>\r\n");
      out.write("                            <span class=\"stat-label\">就職活動中</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <a href=\"StudentServlet\" class=\"card-link\" aria-label=\"学生一覧を表示\">\r\n");
      out.write("                        学生一覧を表示\r\n");
      out.write("                    </a>\r\n");
      out.write("                </article>\r\n");
      out.write("\r\n");
      out.write("                <!-- 新規学生登録 -->\r\n");
      out.write("                <article class=\"management-card\" role=\"article\">\r\n");
      out.write("                    <span class=\"card-icon\" aria-hidden=\"true\">👤</span>\r\n");
      out.write("                    <h3 class=\"card-title\">新規学生登録</h3>\r\n");
      out.write("                    <p class=\"card-description\">\r\n");
      out.write("                        新しい学生の情報を登録し、システムに追加できます。\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <div class=\"card-stats\" role=\"group\" aria-label=\"登録統計\">\r\n");
      out.write("                        <div class=\"stat-item\">\r\n");
      out.write("                            <span class=\"stat-number\">12</span>\r\n");
      out.write("                            <span class=\"stat-label\">今月登録</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"stat-item\">\r\n");
      out.write("                            <span class=\"stat-number\">3</span>\r\n");
      out.write("                            <span class=\"stat-label\">未完了</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <a href=\"StatusServlet?status=createStudent\" class=\"card-link\" aria-label=\"新規学生を登録\">\r\n");
      out.write("                        新規学生を登録\r\n");
      out.write("                    </a>\r\n");
      out.write("                </article>\r\n");
      out.write("            </section>\r\n");
      out.write("        </div>\r\n");
      out.write("    </main>\r\n");
      out.write("\r\n");
      out.write("    <!--▼▼▼▼▼ここから「テキストスライドショー」-->\r\n");
      out.write("    <div class=\"text-slide-wrapper\">\r\n");
      out.write("        <div class=\"text-slide\">\r\n");
      out.write("            <span>Student Management System</span>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--▲▲▲▲▲ここまで「テキストスライドショー」-->\r\n");
      out.write("\r\n");
      out.write("    <!--▼▼▼▼▼ここから「フッター」-->\r\n");
      out.write("    <footer>\r\n");
      out.write("        <div>\r\n");
      out.write("            <p class=\"logo\"><img src=\"images/logo.png\" alt=\"Job Management System\"></p>\r\n");
      out.write("            <ul class=\"icons\">\r\n");
      out.write("                <li><a href=\"#\"><i class=\"fa-brands fa-x-twitter\"></i></a></li>\r\n");
      out.write("                <li><a href=\"#\"><i class=\"fab fa-line\"></i></a></li>\r\n");
      out.write("                <li><a href=\"#\"><i class=\"fab fa-youtube\"></i></a></li>\r\n");
      out.write("                <li><a href=\"#\"><i class=\"fab fa-instagram\"></i></a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <small>Copyright&copy; @ 2025 Job Management System All Rights Reserved.</small>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"javascript:void(0);\" onclick=\"location.reload();\">ホーム</a></li>\r\n");
      out.write("                <!-- 権限に応じた機能リンク -->\r\n");
      out.write("                ");
 if ("teacher".equals(role) || "headmaster".equals(role) || "admin".equals(role)) { 
      out.write("\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/StatusServlet?view=studentManagement\">学生管理</a></li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                ");
 if ("egd".equals(role) || "admin".equals(role)) { 
      out.write("\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/StatusServlet?view=CompanyManagement\">企業管理</a></li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                ");
 if ("teacher".equals(role) || "headmaster".equals(role) || "egd".equals(role) || "admin".equals(role) || "student".equals(role)) { 
      out.write("\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/StatusServlet?view=jobHunting\">就職管理</a></li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                ");
 if ("teacher".equals(role) || "headmaster".equals(role) || "egd".equals(role) || "admin".equals(role)) { 
      out.write("\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/StatusServlet?view=applicantList\">受験者一覧</a></li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                ");
 if ("admin".equals(role)) { 
      out.write("\r\n");
      out.write("                    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/StatusServlet?view=adminDatabase.jsp\">システム管理</a></li>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                <li><a href=\"extension.html\">お問い合わせ</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <!--▲▲▲▲▲ここまで「フッター」-->\r\n");
      out.write("\r\n");
      out.write("    <!--▼▼最下部-->\r\n");
      out.write("    <span class=\"pr\"><a href=\"\" target=\"_blank\">@ 2025 Job Management System</a></span>\r\n");
      out.write("    <!--▲▲ここまで最下部-->\r\n");
      out.write("</div>\r\n");
      out.write("<!--/#container-->\r\n");
      out.write("\r\n");
      out.write("<!--ローディング-->\r\n");
      out.write("<div id=\"loading\">\r\n");
      out.write("    <img src=\"images/logo.png\" alt=\"Loading\">\r\n");
      out.write("    <div class=\"progress-container\">\r\n");
      out.write("        <div class=\"progress-bar\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!--開閉ボタン（ハンバーガーアイコン）-->\r\n");
      out.write("<div id=\"menubar_hdr\">\r\n");
      out.write("    <span></span><span></span><span></span>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!--開閉ブロック-->\r\n");
      out.write("<div id=\"menubar\">\r\n");
      out.write("    <p class=\"logo\"><img src=\"images/logo.png\" alt=\"Job Management System\"></p>\r\n");
      out.write("    <nav>\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li><a href=\"javascript:void(0);\" onclick=\"location.reload();\">ホーム</a></li>\r\n");
      out.write("            <!-- 権限に応じた機能リンク -->\r\n");
      out.write("            ");
 if ("teacher".equals(role) || "headmaster".equals(role) || "admin".equals(role)) { 
      out.write("\r\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/StatusServlet?view=studentManagement\">学生管理</a></li>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            ");
 if ("egd".equals(role) || "admin".equals(role)) { 
      out.write("\r\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/StatusServlet?view=CompanyManagement\">企業管理</a></li>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            ");
 if ("teacher".equals(role) || "headmaster".equals(role) || "egd".equals(role) || "admin".equals(role) || "student".equals(role)) { 
      out.write("\r\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/StatusServlet?view=jobHunting\">就職管理</a></li>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            ");
 if ("teacher".equals(role) || "headmaster".equals(role) || "egd".equals(role) || "admin".equals(role)) { 
      out.write("\r\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/StatusServlet?view=applicantList\">受験者一覧</a></li>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            ");
 if ("admin".equals(role)) { 
      out.write("\r\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/StatusServlet?view=adminDatabase.jsp\">システム管理</a></li>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            <li><a href=\"extension.html\">お問い合わせ</a></li>\r\n");
      out.write("            ");
 if (username != null) { 
      out.write("\r\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/LogoutServlet\">ログアウト</a></li>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("</div>\r\n");
      out.write("<!--/#menubar-->\r\n");
      out.write("\r\n");
      out.write("<!--jQueryの読み込み-->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("<!--パララックス（inview）-->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/protonet-jquery.inview/1.1.2/jquery.inview.min.js\"></script>\r\n");
      out.write("<script src=\"js/jquery.inview_set.js\"></script>\r\n");
      out.write("<!--このテンプレート専用のスクリプト-->\r\n");
      out.write("<script src=\"js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("// 学生管理画面の最適化されたJavaScript\r\n");
      out.write("\r\n");
      out.write("// アクセシビリティの向上\r\n");
      out.write("document.addEventListener('DOMContentLoaded', () => {\r\n");
      out.write("    // キーボードナビゲーションの改善\r\n");
      out.write("    const actionButtons = document.querySelectorAll('.action-btn');\r\n");
      out.write("    actionButtons.forEach(button => {\r\n");
      out.write("        button.addEventListener('keydown', (e) => {\r\n");
      out.write("            if (e.key === 'Enter' || e.key === ' ') {\r\n");
      out.write("                e.preventDefault();\r\n");
      out.write("                button.click();\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    // カードリンクのキーボード操作\r\n");
      out.write("    const cardLinks = document.querySelectorAll('.card-link');\r\n");
      out.write("    cardLinks.forEach(link => {\r\n");
      out.write("        link.addEventListener('keydown', (e) => {\r\n");
      out.write("            if (e.key === 'Enter' || e.key === ' ') {\r\n");
      out.write("                e.preventDefault();\r\n");
      out.write("                link.click();\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    // フォーカス管理の改善\r\n");
      out.write("    const focusableElements = document.querySelectorAll('a, button, input, select, textarea, [tabindex]:not([tabindex=\"-1\"])');\r\n");
      out.write("    focusableElements.forEach(element => {\r\n");
      out.write("        element.addEventListener('focus', () => {\r\n");
      out.write("            element.style.outline = '2px solid #2C7744';\r\n");
      out.write("            element.style.outlineOffset = '2px';\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        element.addEventListener('blur', () => {\r\n");
      out.write("            element.style.outline = '';\r\n");
      out.write("            element.style.outlineOffset = '';\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    // 統計データのアニメーション\r\n");
      out.write("    const statNumbers = document.querySelectorAll('.stat-number');\r\n");
      out.write("    const observer = new IntersectionObserver((entries) => {\r\n");
      out.write("        entries.forEach(entry => {\r\n");
      out.write("            if (entry.isIntersecting) {\r\n");
      out.write("                const target = entry.target;\r\n");
      out.write("                const finalValue = parseInt(target.textContent);\r\n");
      out.write("                animateNumber(target, 0, finalValue, 1000);\r\n");
      out.write("                observer.unobserve(target);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    statNumbers.forEach(stat => observer.observe(stat));\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("// 数値アニメーション関数\r\n");
      out.write("function animateNumber(element, start, end, duration) {\r\n");
      out.write("    const startTime = performance.now();\r\n");
      out.write("    \r\n");
      out.write("    function updateNumber(currentTime) {\r\n");
      out.write("        const elapsed = currentTime - startTime;\r\n");
      out.write("        const progress = Math.min(elapsed / duration, 1);\r\n");
      out.write("        \r\n");
      out.write("        const current = Math.floor(start + (end - start) * progress);\r\n");
      out.write("        element.textContent = current;\r\n");
      out.write("        \r\n");
      out.write("        if (progress < 1) {\r\n");
      out.write("            requestAnimationFrame(updateNumber);\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    requestAnimationFrame(updateNumber);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// パフォーマンス最適化\r\n");
      out.write("window.addEventListener('load', () => {\r\n");
      out.write("    // 画像の遅延読み込み\r\n");
      out.write("    const images = document.querySelectorAll('img[data-src]');\r\n");
      out.write("    const imageObserver = new IntersectionObserver((entries, observer) => {\r\n");
      out.write("        entries.forEach(entry => {\r\n");
      out.write("            if (entry.isIntersecting) {\r\n");
      out.write("                const img = entry.target;\r\n");
      out.write("                img.src = img.dataset.src;\r\n");
      out.write("                img.removeAttribute('data-src');\r\n");
      out.write("                observer.unobserve(img);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    images.forEach(img => imageObserver.observe(img));\r\n");
      out.write("\r\n");
      out.write("    // スムーズスクロール\r\n");
      out.write("    const smoothScrollLinks = document.querySelectorAll('a[href^=\"#\"]');\r\n");
      out.write("    smoothScrollLinks.forEach(link => {\r\n");
      out.write("        link.addEventListener('click', (e) => {\r\n");
      out.write("            e.preventDefault();\r\n");
      out.write("            const targetId = link.getAttribute('href').substring(1);\r\n");
      out.write("            const targetElement = document.getElementById(targetId);\r\n");
      out.write("            \r\n");
      out.write("            if (targetElement) {\r\n");
      out.write("                targetElement.scrollIntoView({\r\n");
      out.write("                    behavior: 'smooth',\r\n");
      out.write("                    block: 'start'\r\n");
      out.write("                });\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("// エラーハンドリング\r\n");
      out.write("window.addEventListener('error', (e) => {\r\n");
      out.write("    console.error('JavaScript error:', e.error);\r\n");
      out.write("    // エラーが発生した場合のフォールバック処理\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("// ページの可視性変更時の処理\r\n");
      out.write("document.addEventListener('visibilitychange', () => {\r\n");
      out.write("    if (document.hidden) {\r\n");
      out.write("        // ページが非表示になった時の処理\r\n");
      out.write("        console.log('Page hidden');\r\n");
      out.write("    } else {\r\n");
      out.write("        // ページが表示された時の処理\r\n");
      out.write("        console.log('Page visible');\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
