/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.28
 * Generated at: 2025-07-02 05:54:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.test;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class TestDashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPではGET、POST、またはHEADのみが許可されます。 JasperはOPTIONSも許可しています。");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>UI確認用テストダッシュボード</title>\n");
      out.write("    <style>\n");
      out.write("        body {\n");
      out.write("            font-family: Arial, sans-serif;\n");
      out.write("            margin: 0;\n");
      out.write("            padding: 20px;\n");
      out.write("            background-color: #f5f5f5;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .container {\n");
      out.write("            max-width: 1200px;\n");
      out.write("            margin: 0 auto;\n");
      out.write("            background-color: white;\n");
      out.write("            padding: 30px;\n");
      out.write("            border-radius: 10px;\n");
      out.write("            box-shadow: 0 2px 10px rgba(0,0,0,0.1);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        h1 {\n");
      out.write("            color: #333;\n");
      out.write("            text-align: center;\n");
      out.write("            margin-bottom: 40px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .warning {\n");
      out.write("            background-color: #fff3cd;\n");
      out.write("            border: 1px solid #ffeaa7;\n");
      out.write("            color: #856404;\n");
      out.write("            padding: 15px;\n");
      out.write("            border-radius: 5px;\n");
      out.write("            margin-bottom: 30px;\n");
      out.write("            text-align: center;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .screen-grid {\n");
      out.write("            display: grid;\n");
      out.write("            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));\n");
      out.write("            gap: 20px;\n");
      out.write("            margin-top: 30px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .screen-card {\n");
      out.write("            background-color: #f8f9fa;\n");
      out.write("            border: 1px solid #dee2e6;\n");
      out.write("            border-radius: 8px;\n");
      out.write("            padding: 20px;\n");
      out.write("            transition: transform 0.2s, box-shadow 0.2s;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .screen-card:hover {\n");
      out.write("            transform: translateY(-5px);\n");
      out.write("            box-shadow: 0 5px 15px rgba(0,0,0,0.1);\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .screen-card h3 {\n");
      out.write("            color: #495057;\n");
      out.write("            margin-top: 0;\n");
      out.write("            margin-bottom: 15px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .screen-card p {\n");
      out.write("            color: #6c757d;\n");
      out.write("            font-size: 14px;\n");
      out.write("            margin-bottom: 15px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .screen-card a {\n");
      out.write("            display: inline-block;\n");
      out.write("            background-color: #007bff;\n");
      out.write("            color: white;\n");
      out.write("            padding: 8px 20px;\n");
      out.write("            text-decoration: none;\n");
      out.write("            border-radius: 5px;\n");
      out.write("            transition: background-color 0.2s;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .screen-card a:hover {\n");
      out.write("            background-color: #0056b3;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .role-section {\n");
      out.write("            margin-bottom: 40px;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        .role-section h2 {\n");
      out.write("            color: #495057;\n");
      out.write("            border-bottom: 2px solid #dee2e6;\n");
      out.write("            padding-bottom: 10px;\n");
      out.write("            margin-bottom: 20px;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <h1>UI確認用テストダッシュボード</h1>\n");
      out.write("        \n");
      out.write("        <div class=\"warning\">\n");
      out.write("            ⚠️ このページは開発・UI確認用です。ログイン認証をバイパスしています。\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"role-section\">\n");
      out.write("            <h2>🎓 学生向け画面</h2>\n");
      out.write("            <div class=\"screen-grid\">\n");
      out.write("                <div class=\"screen-card\">\n");
      out.write("                    <h3>ダッシュボード（学生用）</h3>\n");
      out.write("                    <p>学生用のメインダッシュボード画面です。就活の進捗状況などを確認できます。</p>\n");
      out.write("                    <a href=\"/jms/TestUIServlet?page=dashboard&role=student\">画面を確認</a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"screen-card\">\n");
      out.write("                    <h3>学生情報管理</h3>\n");
      out.write("                    <p>学生の個人情報や就活状況を管理する画面です。</p>\n");
      out.write("                    <a href=\"/jms/TestUIServlet?page=studentManagement&role=student\">画面を確認</a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"role-section\">\n");
      out.write("            <h2>👩‍🏫 教員向け画面</h2>\n");
      out.write("            <div class=\"screen-grid\">\n");
      out.write("                <div class=\"screen-card\">\n");
      out.write("                    <h3>ダッシュボード（教員用）</h3>\n");
      out.write("                    <p>教員用のメインダッシュボード画面です。全体の就活状況を把握できます。</p>\n");
      out.write("                    <a href=\"/jms/TestUIServlet?page=dashboard&role=teacher\">画面を確認</a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"screen-card\">\n");
      out.write("                    <h3>学生一覧</h3>\n");
      out.write("                    <p>登録されている学生の一覧を表示・管理する画面です。</p>\n");
      out.write("                    <a href=\"/jms/TestUIServlet?page=studentList&role=teacher\">画面を確認</a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"screen-card\">\n");
      out.write("                    <h3>学生作成</h3>\n");
      out.write("                    <p>新規学生を登録する画面です。</p>\n");
      out.write("                    <a href=\"/jms/TestUIServlet?page=createStudent&role=teacher\">画面を確認</a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"screen-card\">\n");
      out.write("                    <h3>企業管理</h3>\n");
      out.write("                    <p>就職先企業の情報を管理する画面です。</p>\n");
      out.write("                    <a href=\"/jms/TestUIServlet?page=companyManagement&role=teacher\">画面を確認</a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"screen-card\">\n");
      out.write("                    <h3>面接・試験入力</h3>\n");
      out.write("                    <p>学生の面接や試験の結果を入力する画面です。</p>\n");
      out.write("                    <a href=\"/jms/TestUIServlet?page=interviewExam&role=teacher\">画面を確認</a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"screen-card\">\n");
      out.write("                    <h3>選考ステージ管理</h3>\n");
      out.write("                    <p>就活の選考ステージを管理する画面です。</p>\n");
      out.write("                    <a href=\"/jms/TestUIServlet?page=selectionStage&role=teacher\">画面を確認</a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"screen-card\">\n");
      out.write("                    <h3>テンポラリJMS画面</h3>\n");
      out.write("                    <p>一時的な管理画面やテスト用画面です。</p>\n");
      out.write("                    <a href=\"/jms/TestUIServlet?page=tempJms&role=teacher\">画面を確認</a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"role-section\">\n");
      out.write("            <h2>🔧 その他の画面</h2>\n");
      out.write("            <div class=\"screen-grid\">\n");
      out.write("                <div class=\"screen-card\">\n");
      out.write("                    <h3>ログイン画面</h3>\n");
      out.write("                    <p>通常のログイン画面です。</p>\n");
      out.write("                    <a href=\"/jms/login.html\">画面を確認</a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"screen-card\">\n");
      out.write("                    <h3>ユーザー登録画面</h3>\n");
      out.write("                    <p>新規ユーザーを登録する画面です。</p>\n");
      out.write("                    <a href=\"/jms/register.html\">画面を確認</a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"screen-card\">\n");
      out.write("                    <h3>トップページ</h3>\n");
      out.write("                    <p>アプリケーションのトップページです。</p>\n");
      out.write("                    <a href=\"/jms/index.html\">画面を確認</a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html> ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
